const FEEDBACK_COPY = Object.freeze({
  'en-US': Object.freeze({
    trigger: 'Feedback',
    title: 'Share feedback',
    intro: 'What should we improve?',
    categoryLabel: 'Feedback type',
    categoryPlaceholder: 'Choose one',
    categoryBug: 'Something broke',
    categoryConfusing: 'Hard to use',
    categoryIdea: 'Product idea',
    categoryPraise: 'What worked well',
    categoryOther: 'Something else',
    messageLabel: 'Your feedback',
    messagePlaceholder: 'Tell us what happened or what would make Likerts better.',
    privacy: 'Do not include personal information or research material. We record this message, feedback type, page, and interface language in operational logs.',
    send: 'Send feedback',
    sending: 'Sending…',
    successTitle: 'Thanks—feedback received.',
    successBody: 'We’ll use it to improve Likerts.',
    done: 'Done',
    close: 'Close feedback',
    error: 'Could not send feedback. Please try again.',
  }),
  'zh-CN': Object.freeze({
    trigger: '反馈',
    title: '分享反馈',
    intro: '我们应该改进什么？',
    categoryLabel: '反馈类型',
    categoryPlaceholder: '请选择',
    categoryBug: '出现故障',
    categoryConfusing: '难以使用',
    categoryIdea: '产品建议',
    categoryPraise: '做得好的地方',
    categoryOther: '其他',
    messageLabel: '您的反馈',
    messagePlaceholder: '请告诉我们发生了什么，或怎样能让 Likerts 更好用。',
    privacy: '请勿包含个人信息或研究材料。我们会在运行日志中记录此消息、反馈类型、页面和界面语言。',
    send: '发送反馈',
    sending: '正在发送…',
    successTitle: '谢谢，反馈已收到。',
    successBody: '我们会用它来改进 Likerts。',
    done: '完成',
    close: '关闭反馈',
    error: '无法发送反馈，请重试。',
  }),
  'ja-JP': Object.freeze({
    trigger: 'フィードバック',
    title: 'フィードバックを送る',
    intro: '改善してほしい点を教えてください。',
    categoryLabel: 'フィードバックの種類',
    categoryPlaceholder: '選択してください',
    categoryBug: '不具合があった',
    categoryConfusing: '使いにくかった',
    categoryIdea: '製品への提案',
    categoryPraise: '良かった点',
    categoryOther: 'その他',
    messageLabel: 'フィードバック',
    messagePlaceholder: '起きたこと、または Likerts をより良くする方法を教えてください。',
    privacy: '個人情報や調査資料は含めないでください。このメッセージ、種類、ページ、表示言語を運用ログに記録します。',
    send: '送信する',
    sending: '送信中…',
    successTitle: 'ありがとうございます。受け付けました。',
    successBody: 'Likerts の改善に活用します。',
    done: '完了',
    close: 'フィードバックを閉じる',
    error: '送信できませんでした。もう一度お試しください。',
  }),
  'ko-KR': Object.freeze({
    trigger: '피드백',
    title: '피드백 보내기',
    intro: '무엇을 개선하면 좋을까요?',
    categoryLabel: '피드백 유형',
    categoryPlaceholder: '선택하세요',
    categoryBug: '문제가 발생함',
    categoryConfusing: '사용하기 어려움',
    categoryIdea: '제품 아이디어',
    categoryPraise: '잘 작동한 점',
    categoryOther: '기타',
    messageLabel: '피드백',
    messagePlaceholder: '무슨 일이 있었는지 또는 Likerts를 어떻게 개선하면 좋을지 알려 주세요.',
    privacy: '개인 정보나 연구 자료를 포함하지 마세요. 이 메시지, 피드백 유형, 페이지 및 인터페이스 언어가 운영 로그에 기록됩니다.',
    send: '피드백 보내기',
    sending: '보내는 중…',
    successTitle: '감사합니다. 피드백을 받았습니다.',
    successBody: 'Likerts를 개선하는 데 활용하겠습니다.',
    done: '완료',
    close: '피드백 닫기',
    error: '피드백을 보낼 수 없습니다. 다시 시도해 주세요.',
  }),
});

export function localizedFeedbackCopy(locale) {
  return FEEDBACK_COPY[locale] || FEEDBACK_COPY['en-US'];
}
