import Foundation

public struct OfflineLimits: Sendable { public var maxRecords=1000,maxBytes=10*1024*1024,maxAgeSeconds=7*86400;public init(maxRecords:Int=1000,maxBytes:Int=10*1024*1024,maxAgeSeconds:Int=7*86400)throws{guard (1...10000).contains(maxRecords),(1...100*1024*1024).contains(maxBytes),(1...30*86400).contains(maxAgeSeconds)else{throw OfflineQueueError.invalidLimits};self.maxRecords=maxRecords;self.maxBytes=maxBytes;self.maxAgeSeconds=maxAgeSeconds}}
public enum OfflineQueueError:Error{case invalidLimits,recordTooLarge,capacity,idempotencyConflict,flushActive,insecureAdapter}
public enum OfflineBlockedReason:String,Codable,Sendable{case invalid,conflict,unauthorized,revoked,deleted,expired}
public struct OfflineQueueStatus:Sendable,Equatable{public let pending:Int,blocked:[OfflineBlockedReason:Int],expiredLocal:Int,quarantined:Int,bytes:Int}
public struct OfflineAttempt:Sendable{public let status:Int,responseId:String?,receiptCollectionId:String?,accepted:Bool,retryAfterSeconds:Int?;public init(status:Int,responseId:String?=nil,receiptCollectionId:String?=nil,accepted:Bool=false,retryAfterSeconds:Int?=nil){self.status=status;self.responseId=responseId;self.receiptCollectionId=receiptCollectionId;self.accepted=accepted;self.retryAfterSeconds=retryAfterSeconds}}
public protocol OfflineSecureAdapter:Sendable{var protectionProfile:String{get};func load()async throws->[Data];func replace(_ records:[Data])async throws;func seal(_ clear:Data)async throws->Data;func open(_ sealed:Data)async throws->Data}
private struct Envelope:Codable{var id:String,collectionId:String,submission:Data,idempotencyKey:String;var createdAt:Date;var byteSize:Int,attemptCount:Int;var state:String;var reason:OfflineBlockedReason?}
public struct OfflineOutcome:Sendable{public let recordId:String,outcome:String,reason:OfflineBlockedReason?,retryAfterSeconds:Int?}
public struct OfflineFlushReport:Sendable{public var attempted=0,accepted=0;public var cancelled=false;public var outcomes:[OfflineOutcome]=[];public let status:OfflineQueueStatus}
public actor OfflineQueue{
 let adapter:OfflineSecureAdapter,limits:OfflineLimits,now:@Sendable()->Date;var flushing=false
 public init(adapter:OfflineSecureAdapter,limits:OfflineLimits=try! OfflineLimits(),now:@escaping @Sendable()->Date={Date()})throws{guard adapter.protectionProfile=="keychain_device_only_aes_gcm"else{throw OfflineQueueError.insecureAdapter};self.adapter=adapter;self.limits=limits;self.now=now}
 private func read()async throws->([Envelope],[Data]){var good:[Envelope]=[],bad:[Data]=[];for sealed in try await adapter.load(){do{good.append(try JSONDecoder().decode(Envelope.self,from:try await adapter.open(sealed)))}catch{bad.append(sealed)}};return(good,bad)}
 private func write(_ values:[Envelope],_ bad:[Data])async throws{var sealed=bad;for value in values{sealed.append(try await adapter.seal(JSONEncoder().encode(value)))};try await adapter.replace(sealed)}
 public func enqueue(collectionId:String,submission:Data,idempotencyKey:String)async throws->String{guard submission.count<=65536 else{throw OfflineQueueError.recordTooLarge};let(good,bad)=try await read();if let prior=good.first(where:{$0.idempotencyKey==idempotencyKey}){guard prior.collectionId==collectionId&&prior.submission==submission else{throw OfflineQueueError.idempotencyConflict};return prior.id};guard good.count<limits.maxRecords&&good.reduce(0,{$0+$1.byteSize})+submission.count<=limits.maxBytes else{throw OfflineQueueError.capacity};let value=Envelope(id:UUID().uuidString,collectionId:collectionId,submission:submission,idempotencyKey:idempotencyKey,createdAt:now(),byteSize:submission.count,attemptCount:0,state:"pending");try await write(good+[value],bad);return value.id}
 public func snapshot()async throws->OfflineQueueStatus{let(good,bad)=try await read();var pending=0,expired=0,blocked:[OfflineBlockedReason:Int]=[:],bytes=0;for r in good{bytes+=r.byteSize;if r.state=="pending"{pending+=1}else if r.state=="expired_local"{expired+=1}else if let reason=r.reason{blocked[reason,default:0]+=1}};return .init(pending:pending,blocked:blocked,expiredLocal:expired,quarantined:bad.count,bytes:bytes)}
 public func delete(_ id:String)async throws{let(good,bad)=try await read();try await write(good.filter{$0.id != id},bad)}
 public func deleteCollection(_ id:String)async throws->Int{let(good,bad)=try await read(),kept=good.filter{$0.collectionId != id};try await write(kept,bad);return good.count-kept.count}
 public func purgeQuarantined()async throws->Int{let(good,bad)=try await read();try await write(good,[]);return bad.count}
 public func flush(cancelled:@Sendable()->Bool={false},credential:@Sendable(String)async->String?,send:@Sendable(String,String,Data)async->OfflineAttempt)async throws->OfflineFlushReport{guard !flushing else{throw OfflineQueueError.flushActive};flushing=true;defer{flushing=false};var(initial,initialBad)=try await read();var expiredChanged=false;for index in initial.indices where initial[index].state != "expired_local" && now().timeIntervalSince(initial[index].createdAt)>Double(limits.maxAgeSeconds){initial[index].state="expired_local";initial[index].reason=nil;expiredChanged=true};if expiredChanged{try await write(initial,initialBad)};let ids=initial.filter{$0.state=="pending"}.sorted{$0.createdAt==$1.createdAt ? $0.id<$1.id:$0.createdAt<$1.createdAt}.map(\.id);var attempted=0,accepted=0,wasCancelled=false,outcomes:[OfflineOutcome]=[];for id in ids{if cancelled(){wasCancelled=true;break};var(good,bad)=try await read();guard let index=good.firstIndex(where:{$0.id==id&&$0.state=="pending"})else{continue};guard let token=await credential(good[index].collectionId)else{outcomes.append(.init(recordId:id,outcome:"credential_unavailable",reason:nil,retryAfterSeconds:nil));continue};attempted+=1;let attempt=await send(good[index].collectionId,token,good[index].submission);(good,bad)=try await read();guard let fresh=good.firstIndex(where:{$0.id==id})else{continue};if (200..<300).contains(attempt.status) && attempt.accepted && attempt.receiptCollectionId==good[fresh].collectionId && !(attempt.responseId?.isEmpty ?? true){good.remove(at:fresh);try await write(good,bad);accepted+=1;outcomes.append(.init(recordId:id,outcome:"accepted",reason:nil,retryAfterSeconds:nil))}else{good[fresh].attemptCount+=1;let reasons=[400:OfflineBlockedReason.invalid,409:.conflict,401:.unauthorized,403:.revoked,404:.deleted,410:.expired];let retry=[408,425,429].contains(attempt.status)||attempt.status>=500;let terminal=reasons[attempt.status] ?? ((400..<500).contains(attempt.status) && !retry ? .invalid:nil);if let reason=terminal{good[fresh].state="blocked";good[fresh].reason=reason;outcomes.append(.init(recordId:id,outcome:"blocked",reason:reason,retryAfterSeconds:nil))}else{outcomes.append(.init(recordId:id,outcome:"retry",reason:nil,retryAfterSeconds:retry ? attempt.retryAfterSeconds.map{min(86400,max(0,$0))}:nil))};try await write(good,bad)}};return .init(attempted:attempted,accepted:accepted,cancelled:wasCancelled,outcomes:outcomes,status:try await snapshot())}
}
