import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { spawn, execFileSync } from 'node:child_process';
import { createServer as netServer } from 'node:net';
import { fileURLToPath } from 'node:url';
import { LikertsClient as WebClient } from '../sdks/web/dist/index.js';
import { LikertsClient, capabilities } from '../tools/mcp/dist/client.js';
import { createServer } from '../tools/mcp/dist/server.js';
import { Client } from '../tools/mcp/node_modules/@modelcontextprotocol/sdk/dist/esm/client/index.js';
import { InMemoryTransport } from '../tools/mcp/node_modules/@modelcontextprotocol/sdk/dist/esm/inMemory.js';
const root=fileURLToPath(new URL('../',import.meta.url));
const fixture=JSON.parse(await readFile(new URL('../contracts/survey.example.json',import.meta.url)));
const submission=JSON.parse(await readFile(new URL('../contracts/response.example.json',import.meta.url)));
const sdkCapabilities={installations:[{target:'web',sdkVersion:'0.0.1',schemaVersions:[1,2]}]};
const mixedSdkCapabilities={installations:[{target:'web',sdkVersion:'legacy',schemaVersions:[1]},{target:'web',sdkVersion:'0.0.1',schemaVersions:[1,2]}]};
const probe=netServer(); await new Promise(resolve=>probe.listen(0,'127.0.0.1',resolve));const port=probe.address().port;await new Promise(resolve=>probe.close(resolve));
const base=`http://127.0.0.1:${port}`;
const tokenA='integration-alpha-token-not-production';const tokenB='integration-bravo-token-not-production';
const child=spawn(`${root}backend/target/debug/likerts-server`,[],{env:{...process.env,LIKERTS_PORT:String(port),LIKERTS_ADMISSION_MODE:'disabled',LIKERTS_ADMISSION_REST_URL:undefined,LIKERTS_ADMISSION_REST_TOKEN:undefined,LIKERTS_ALLOW_MEMORY:'1',LIKERTS_DEV_TOKENS:JSON.stringify({[tokenA]:'alpha',[tokenB]:'bravo'})},stdio:['ignore','ignore','pipe']});
let logs='';child.stderr.on('data',c=>logs+=c.toString());
let mcp;let server;
try{
 let ready=false;for(let i=0;i<100;i++){try{if((await fetch(`${base}/health`)).ok){ready=true;break}}catch{} await new Promise(r=>setTimeout(r,50));}
 assert(ready,`Backend did not start: ${logs}`);
 const cli=(op,input={})=>JSON.parse(execFileSync(`${root}tools/cli/target/debug/likerts`,['call',op,'--input','-'],{input:JSON.stringify(input),encoding:'utf8',env:{...process.env,LIKERTS_API_URL:base,LIKERTS_TOKEN:tokenA}}));
 const survey=cli('surveys_create',{idempotencyKey:'integration-survey',...fixture});assert.equal(survey.revision,1);
 assert.equal(cli('surveys_create',{idempotencyKey:'integration-survey',...fixture}).id,survey.id);
 const api=new LikertsClient(base,tokenA);server=createServer(api);mcp=new Client({name:'integration',version:'1.0.0'});
 const [left,right]=InMemoryTransport.createLinkedPair();await Promise.all([server.connect(left),mcp.connect(right)]);
 const inventory=await mcp.listTools();assert.deepEqual(inventory.tools.map(t=>t.name).sort(),capabilities.map(c=>c.name).sort());
 const call=async(name,args)=>{const result=await mcp.callTool({name,arguments:args});assert(!result.isError,JSON.stringify(result));return JSON.parse(result.content[0].text)};
 const assertUsage=(usage,count)=>{assert.deepEqual(usage,{acceptedResponses:count,monthAcceptedResponses:count});};
 const version=await call('surveys_publish',{id:survey.id,revision:survey.revision,sdkCapabilities:mixedSdkCapabilities});
 const c=await call('collections_create',{idempotencyKey:'integration-collection',surveyId:survey.id,version:version.version,placement:'checkout',sdkCapabilities:mixedSdkCapabilities});
 assert.deepEqual(await call('collections_create',{idempotencyKey:'integration-collection',surveyId:survey.id,version:version.version,placement:'checkout',sdkCapabilities:mixedSdkCapabilities}),c);
 await assert.rejects(()=>call('collections_create',{idempotencyKey:'integration-collection',surveyId:survey.id,version:version.version,placement:'changed',sdkCapabilities:mixedSdkCapabilities}),/409/);
 const web=new WebClient(base,c.token);const config=await web.collection(c.id);assert.equal(config.schema.schemaVersion,1);assert.deepEqual(config.schema.questions,fixture.questions);
 const receipts=await Promise.all(Array.from({length:16},()=>web.submit(c.id,submission)));assert(receipts.every(r=>r.responseId===receipts[0].responseId));assert.equal(receipts[0].accepted,true);
 assertUsage(await call('usage_get',{}),1);
 const other=new LikertsClient(base,tokenB);assert.deepEqual(await other.call('responses_list',{}),{items:[],nextCursor:null});assert.deepEqual(await other.call('surveys_list',{}),[]);
 await assert.rejects(()=>other.call('surveys_publish',{id:survey.id,revision:1,sdkCapabilities}),/404/);
 await assert.rejects(()=>new LikertsClient(base,c.token).call('responses_list',{}),/401/);
 await assert.rejects(()=>new WebClient(base,tokenA).collection(c.id),/401|404/);
 await assert.rejects(()=>web.submit(c.id,{...submission,answers:{rating:1}}),e=>e.status===409);
 await assert.rejects(()=>web.submit(c.id,{...submission,idempotencyKey:'bad-rating',answers:{rating:6}}),e=>e.status===400);
 await call('collections_update',{id:c.id,accepting:false});
 assert.equal((await web.submit(c.id,submission)).responseId,receipts[0].responseId);
 await assert.rejects(()=>web.submit(c.id,{...submission,idempotencyKey:'new-after-close'}),e=>e.status===409);
 const malformed=await fetch(`${base}/v1/surveys`,{method:'POST',headers:{authorization:`Bearer ${tokenA}`,'content-type':'application/json'},body:'{broken'});assert.equal(malformed.status,400);assert.equal((await malformed.json()).error.code,'invalid_request');
 const final=await call('usage_get',{});assert.equal(final.acceptedResponses,1);
 const limited=cli('collections_create',{idempotencyKey:'limited-collection',surveyId:survey.id,version:version.version,placement:'limited-checkout',expiresAt:new Date(Date.now()+60_000).toISOString(),responseCap:1,sdkCapabilities});
 assert.equal(limited.responseCap,1);assert.equal(limited.revoked,false);assert(limited.expiresAt);
 const limitedWeb=new WebClient(base,limited.token);
 const limitedSubmission={...submission,idempotencyKey:'limited-first'};
 const limitedReceipt=await limitedWeb.submit(limited.id,limitedSubmission);
 assert.equal((await limitedWeb.submit(limited.id,limitedSubmission)).responseId,limitedReceipt.responseId);
 await assert.rejects(()=>limitedWeb.submit(limited.id,{...submission,idempotencyKey:'limited-second'}),e=>e.status===409);
 assert.deepEqual(await call('collections_update',{id:limited.id,revoke:true}),{accepting:false,id:limited.id,revoked:true});
 await assert.rejects(()=>limitedWeb.submit(limited.id,limitedSubmission),e=>e.status===410);
 await assert.rejects(()=>limitedWeb.collection(limited.id),e=>e.status===410);
 assertUsage(await call('usage_get',{}),2);
 const expandedFixture=JSON.parse(await readFile(new URL('../contracts/expanded-survey.example.json',import.meta.url)));
 const expandedSubmission=JSON.parse(await readFile(new URL('../contracts/expanded-response.example.json',import.meta.url)));
 const expanded=cli('surveys_create',{idempotencyKey:'expanded-survey',...expandedFixture});
 await assert.rejects(()=>call('surveys_publish',{id:expanded.id,revision:expanded.revision,sdkCapabilities:mixedSdkCapabilities}),/400/);
 const expandedVersion=await call('surveys_publish',{id:expanded.id,revision:expanded.revision,sdkCapabilities});
 await assert.rejects(()=>call('collections_create',{idempotencyKey:'incompatible-expanded',surveyId:expanded.id,version:expandedVersion.version,placement:'expanded-checkout',sdkCapabilities:mixedSdkCapabilities}),/400/);
 const ec=await call('collections_create',{idempotencyKey:'expanded-collection',surveyId:expanded.id,version:expandedVersion.version,placement:'expanded-checkout',sdkCapabilities});
 const ew=new WebClient(base,ec.token);const es=await ew.collection(ec.id);
 assert.equal(es.schema.schemaVersion,2);assert.deepEqual(es.schema.questions,expandedFixture.questions);
 for (const invalid of [{...expandedSubmission.answers,recommend:11},{...expandedSubmission.answers,return:true},{...expandedSubmission.answers,improvements:[]},{...expandedSubmission.answers,improvements:['speed','payment','navigation']}]) {
   await assert.rejects(()=>ew.submit(ec.id,{...expandedSubmission,idempotencyKey:'invalid-expanded',answers:invalid}),e=>e.status===400);
 }
 assert.equal((await call('usage_get',{})).acceptedResponses,2);
 const enhancedReceipts=await Promise.all(Array.from({length:8},()=>ew.submit(ec.id,expandedSubmission)));
 assert(enhancedReceipts.every(r=>r.responseId===enhancedReceipts[0].responseId));
 assertUsage(await call('usage_get',{}),3);
 const filtered=cli('responses_list',{collectionId:ec.id,limit:1});assert.equal(filtered.items.length,1);assert.equal(filtered.items[0].receipt.responseId,enhancedReceipts[0].responseId);assert.equal(filtered.nextCursor,null);assert(filtered.items[0].acceptedAt);
 const responsePage1=await call('responses_list',{limit:2});assert.equal(responsePage1.items.length,2);assert(responsePage1.nextCursor);
 const acceptedDuringTraversal=await ew.submit(ec.id,{...expandedSubmission,idempotencyKey:'accepted-during-pagination'});assert(acceptedDuringTraversal.responseId);
 const responsePage2=await call('responses_list',{cursor:responsePage1.nextCursor});assert.equal(responsePage2.items.length,1);assert.equal(responsePage2.nextCursor,null);
 assert.equal(new Set([...responsePage1.items,...responsePage2.items].map(item=>item.receipt.responseId)).size,3);
 assert.deepEqual((await call('responses_list',{cursor:responsePage1.nextCursor})).items,responsePage2.items);
 await assert.rejects(()=>api.call('responses_list',{cursor:responsePage1.nextCursor,limit:3}),/400/);
 assert.equal((await call('responses_list',{})).items.length,4);
 const malformedQuery=await fetch(`${base}/v1/responses?acceptedFrom=wrong`,{headers:{authorization:`Bearer ${tokenA}`}});assert.equal(malformedQuery.status,400);assert.equal((await malformedQuery.json()).error.code,'invalid_request');
 const exportJob=await call('exports_create',{idempotencyKey:'integration-json-export',format:'json'});assert.equal(exportJob.status,'queued');
 const acceptedAfterExport=await ew.submit(ec.id,{...expandedSubmission,idempotencyKey:'accepted-after-export-snapshot'});
 const waitExport=async id=>{for(let i=0;i<100;i++){const job=await call('exports_get',{id});if(job.status==='ready'||job.status==='failed')return job;await new Promise(r=>setTimeout(r,10));}throw new Error('export did not finish')};
 const readyExport=await waitExport(exportJob.id);assert.equal(readyExport.status,'ready');assert.equal(Date.parse(readyExport.expiresAt)-Date.parse(readyExport.createdAt),86_400_000);assert.equal(readyExport.responseCount,4);assert.equal(readyExport.manifest.schemas.length,2);
 const jsonDownload=await call('exports_download',{id:exportJob.id});const jsonFile=JSON.parse(Buffer.from(jsonDownload.contentBase64,'base64'));assert.equal(jsonFile.responses.length,4);assert.deepEqual(jsonFile.manifest,readyExport.manifest);
 assert.equal((await call('exports_create',{idempotencyKey:'integration-json-export',format:'json'})).id,exportJob.id);
 await assert.rejects(()=>api.call('exports_create',{idempotencyKey:'integration-json-export',format:'csv'}),/409/);
 const csvJob=cli('exports_create',{idempotencyKey:'integration-csv-export',format:'csv',collectionId:ec.id});await waitExport(csvJob.id);
 const csvDownload=cli('exports_download',{id:csvJob.id});const csvFile=Buffer.from(csvDownload.contentBase64,'base64').toString();assert(csvFile.startsWith('response_id,collection_id,accepted_at,answers_json,metadata_json\r\n'));assert.equal(csvDownload.manifest.responseCount,3);
 await assert.rejects(()=>other.call('exports_get',{id:exportJob.id}),/404/);
 assert.deepEqual(await call('exports_revoke',{id:exportJob.id}),{});await assert.rejects(()=>api.call('exports_download',{id:exportJob.id}),/410/);
 const usageBeforeDelete=await call('usage_get',{});
 assert.deepEqual(await call('responses_delete',{id:acceptedAfterExport.responseId}),{});
 assert.deepEqual(await call('usage_get',{}),usageBeforeDelete);
 assert.equal((await call('responses_list',{})).items.some(item=>item.receipt.responseId===acceptedAfterExport.responseId),false);
 assert.equal((await ew.submit(ec.id,{...expandedSubmission,idempotencyKey:'accepted-after-export-snapshot'})).responseId,acceptedAfterExport.responseId);
 await assert.rejects(()=>ew.submit(ec.id,{...expandedSubmission,idempotencyKey:'accepted-after-export-snapshot',answers:{...expandedSubmission.answers,recommend:1}}),e=>e.status===409);
 await assert.rejects(()=>api.call('exports_download',{id:csvJob.id}),/410/);
 const securityCollection=await call('collections_create',{idempotencyKey:'security-collection',surveyId:survey.id,version:version.version,placement:'security',sdkCapabilities});
 assert.deepEqual(await call('collections_security_update',{id:securityCollection.id,allowedOrigins:[base],requestsPerMinute:2}),{collectionId:securityCollection.id,allowedOrigins:[base],requestsPerMinute:2});
 const preflight=await fetch(`${base}/v1/collections/${securityCollection.id}/responses`,{method:'OPTIONS',headers:{origin:base,'access-control-request-method':'POST','access-control-request-headers':'authorization,content-type'}});assert.equal(preflight.status,204);assert.equal(preflight.headers.get('access-control-allow-origin'),base);assert.match(preflight.headers.get('access-control-allow-headers'),/Authorization/);
 const badPreflight=await fetch(`${base}/v1/collections/${securityCollection.id}/responses`,{method:'OPTIONS',headers:{origin:'https://evil.example','access-control-request-method':'POST'}});assert.equal(badPreflight.status,403);
 const usageBeforeRate=await call('usage_get',{});
 for(let i=0;i<2;i++){const invalid=await fetch(`${base}/v1/collections/${securityCollection.id}/responses`,{method:'POST',headers:{origin:base,authorization:`Bearer ${securityCollection.token}`,'content-type':'application/json'},body:JSON.stringify({...submission,idempotencyKey:`rate-invalid-${i}`,answers:{rating:99}})});assert.equal(invalid.status,400);assert.equal(invalid.headers.get('access-control-allow-origin'),base)}
 const limitedRate=await fetch(`${base}/v1/collections/${securityCollection.id}/responses`,{method:'POST',headers:{origin:base,authorization:`Bearer ${securityCollection.token}`,'content-type':'application/json'},body:JSON.stringify({...submission,idempotencyKey:'rate-third'})});assert.equal(limitedRate.status,429);assert.equal(limitedRate.headers.get('retry-after'),'60');assert.equal(limitedRate.headers.get('access-control-allow-origin'),base);assert.deepEqual(await call('usage_get',{}),usageBeforeRate);
 const retryCollection=await call('collections_create',{idempotencyKey:'rate-retry-collection',surveyId:survey.id,version:version.version,placement:'rate-retry',sdkCapabilities});
 await call('collections_security_update',{id:retryCollection.id,allowedOrigins:[base],requestsPerMinute:1});
 const retryPayload={...submission,idempotencyKey:'accepted-before-rate-limit'};
 const firstAtLimit=await fetch(`${base}/v1/collections/${retryCollection.id}/responses`,{method:'POST',headers:{origin:base,authorization:`Bearer ${retryCollection.token}`,'content-type':'application/json'},body:JSON.stringify(retryPayload)});assert.equal(firstAtLimit.status,200);const firstAtLimitReceipt=await firstAtLimit.json();
 const terminalRetry=await fetch(`${base}/v1/collections/${retryCollection.id}/responses`,{method:'POST',headers:{origin:base,authorization:`Bearer ${retryCollection.token}`,'content-type':'application/json'},body:JSON.stringify(retryPayload)});assert.equal(terminalRetry.status,200);assert.equal((await terminalRetry.json()).responseId,firstAtLimitReceipt.responseId);
 const changedRetry=await fetch(`${base}/v1/collections/${retryCollection.id}/responses`,{method:'POST',headers:{origin:base,authorization:`Bearer ${retryCollection.token}`,'content-type':'application/json'},body:JSON.stringify({...retryPayload,answers:{rating:4}})});assert.equal(changedRetry.status,409);
 const newAtLimit=await fetch(`${base}/v1/collections/${retryCollection.id}/responses`,{method:'POST',headers:{origin:base,authorization:`Bearer ${retryCollection.token}`,'content-type':'application/json'},body:JSON.stringify({...submission,idempotencyKey:'new-after-rate-limit'})});assert.equal(newAtLimit.status,429);
 assert.deepEqual(await call('retention_run',{}),{responsesErased:0,exportsRevoked:0});
 const usageAfterRateTest=await call('usage_get',{});assert.equal(usageAfterRateTest.acceptedResponses,usageBeforeDelete.acceptedResponses+1);
 assert.equal((await ew.submit(ec.id,{...expandedSubmission,idempotencyKey:'accepted-after-export-snapshot'})).responseId,acceptedAfterExport.responseId);
 assert.deepEqual(await other.call('responses_list',{}),{items:[],nextCursor:null});
 assert.deepEqual(await call('workspace_delete',{}),{});
 await assert.rejects(()=>api.call('responses_list',{}),/401/);
 console.log('PASS: CLI → MCP → Web SDK; idempotent management creation; declared mixed-fleet compatibility; immutable bindings; unmetered response counting; stable pagination and export snapshots; erasure; tenant and credential isolation; validation; collection caps; revocation; operation parity.');
}finally{await mcp?.close();await server?.close();child.kill('SIGTERM');}
