import assert from 'node:assert/strict';
import {spawn,execFileSync} from 'node:child_process';
import {createServer as netServer} from 'node:net';
import {fileURLToPath} from 'node:url';
import {LikertsClient} from '../tools/mcp/dist/client.js';
import {createServer} from '../tools/mcp/dist/server.js';
import {Client} from '../tools/mcp/node_modules/@modelcontextprotocol/sdk/dist/esm/client/index.js';
import {InMemoryTransport} from '../tools/mcp/node_modules/@modelcontextprotocol/sdk/dist/esm/inMemory.js';
const root=fileURLToPath(new URL('../',import.meta.url)),database=process.env.LIKERTS_WEBHOOK_TEST_API_URL;
assert(database,'Run scripts/check-webhook-isolation.sh for a restricted PostgreSQL fixture');
const probe=netServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));
const base=`http://127.0.0.1:${port}`,token='webhook-http-local-admin-a',other='webhook-http-local-admin-b';
const env={...process.env,DATABASE_URL:database,LIKERTS_ALLOW_DEV_AUTH:'1',LIKERTS_ADMISSION_MODE:'disabled',LIKERTS_ADMISSION_REST_URL:undefined,LIKERTS_ADMISSION_REST_TOKEN:undefined,LIKERTS_ALLOW_MEMORY:'0',LIKERTS_RUN_MIGRATIONS:'0',LIKERTS_PORT:String(port),LIKERTS_DEV_TOKENS:JSON.stringify({[token]:'webhook-http-a',[other]:'webhook-http-b'}),LIKERTS_COLLECTION_CREDENTIAL_KEY:Buffer.alloc(32,6).toString('base64'),LIKERTS_WEBHOOK_CREDENTIAL_KEY:Buffer.alloc(32,73).toString('base64')};
const child=spawn(`${root}backend/target/debug/likerts-server`,[],{env,stdio:['ignore','ignore','pipe']});let logs='',server,mcp;child.stderr.on('data',v=>logs+=v);
try {
 let ready=false;for(let i=0;i<100;i++){try{if((await fetch(base+'/health')).ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,50))}assert(ready,logs);
 const cli=(op,input)=>JSON.parse(execFileSync(`${root}tools/cli/target/debug/likerts`,['call',op,'--input','-'],{input:JSON.stringify(input),encoding:'utf8',env:{...process.env,LIKERTS_API_URL:base,LIKERTS_TOKEN:token}}));
 server=createServer(new LikertsClient(base,token));mcp=new Client({name:'webhook-integration',version:'1.0.0'});const[left,right]=InMemoryTransport.createLinkedPair();await Promise.all([server.connect(left),mcp.connect(right)]);
 const call=async(name,args={})=>{const result=await mcp.callTool({name,arguments:args});assert(!result.isError,JSON.stringify(result));return JSON.parse(result.content[0].text)};
 const request=async(path,method='GET',input,auth=token)=>fetch(base+path,{method,headers:{authorization:`Bearer ${auth}`,'content-type':'application/json'},...(input?{body:JSON.stringify(input)}:{})});
 const created=cli('webhook_endpoints_create',{idempotencyKey:'endpoint',url:'https://hooks.customer.com/likerts'});assert.equal(created.endpoint.enabled,false);assert.match(created.signingSecret,/^whsec_/);
 assert.deepEqual(cli('webhook_endpoints_create',{idempotencyKey:'endpoint',url:'https://hooks.customer.com/likerts'}),created);
 const listed=await call('webhook_endpoints_list');assert.equal(listed.length,1);assert(!JSON.stringify(listed).includes('whsec_'));
 assert.equal((await request(`/v1/webhook-endpoints/${created.endpoint.id}`,'PATCH',{enabled:true},other)).status,404);
 const bad=await request('/v1/webhook-endpoints','POST',{idempotencyKey:'bad',url:'https://127.0.0.1/'});assert.equal(bad.status,400);assert.equal((await bad.json()).error.code,'invalid_request');
 const reader=await call('service_credentials_create',{name:'Webhook reader',scopes:['webhooks:read'],expiresAt:new Date(Date.now()+3600000).toISOString()});
 assert.equal((await request('/v1/webhook-endpoints','GET',undefined,reader.token)).status,200);assert.equal((await request('/v1/webhook-endpoints','POST',{idempotencyKey:'forbidden',url:'https://hooks.customer.com/reader'},reader.token)).status,403);
 assert.deepEqual(created.endpoint.eventTypes,['response.accepted']);
 const writer=await call('service_credentials_create',{name:'Webhook writer only',scopes:['webhooks:write'],expiresAt:new Date(Date.now()+3600000).toISOString()});
 assert.equal((await request(`/v1/webhook-endpoints/${created.endpoint.id}`,'PATCH',{eventTypes:['response.accepted']})).status,400,'subscriptions are immutable');
 for(const eventTypes of [[],['unknown'],['response.accepted','response.accepted']]) assert.equal((await request('/v1/webhook-endpoints','POST',{idempotencyKey:'invalid-event-types',url:'https://hooks.customer.com/',eventTypes})).status,400);
 assert.equal((await request('/v1/webhook-endpoints','POST',{idempotencyKey:'unsupported-event-type',url:'https://hooks.customer.com/',eventTypes:['survey.published']},writer.token)).status,400);
 cli('webhook_endpoints_update',{id:created.endpoint.id,enabled:true});
 const rotated=await call('webhook_endpoints_rotate',{id:created.endpoint.id,idempotencyKey:'rotate'});assert.notEqual(rotated.signingSecret,created.signingSecret);
 const fleet={installations:[{target:'web',sdkVersion:'0.0.1',schemaVersions:[1,2]}]};
 const survey=await call('surveys_create',{idempotencyKey:'survey',title:'Response callback',questions:[{id:'comment',type:'text',label:'Comment',required:true,maxLength:500}]});
 const version=await call('surveys_publish',{id:survey.id,revision:1,sdkCapabilities:fleet});
 const collection=await call('collections_create',{idempotencyKey:'collection',surveyId:survey.id,version:version.version,placement:'app',sdkCapabilities:fleet});
 const body={idempotencyKey:'once',answers:{comment:'must not enter callback'},metadata:{private:'never-send'}};
 const replies=await Promise.all(Array.from({length:8},()=>request(`/v1/collections/${collection.id}/responses`,'POST',body,collection.token).then(async r=>{assert.equal(r.status,200);return r.json()})));assert(replies.every(r=>r.responseId===replies[0].responseId));
 const deliveries=await call('webhook_deliveries_list',{endpointId:created.endpoint.id,limit:100});assert.equal(deliveries.length,1);assert.equal((await call('usage_get')).acceptedResponses,1);
 const delivery=cli('webhook_deliveries_get',{id:deliveries[0].id});assert.equal(delivery.status,'queued');
 assert.equal((await request(`/v1/webhook-deliveries/${delivery.id}`,'GET',undefined,other)).status,404);
 assert.equal((await request('/v1/webhook-deliveries?limit=oops')).status,400);
 assert.match(delivery.id,/^[a-f0-9-]{36}$/);
 // Deterministic failure fixture: lifecycle Rust tests separately exercise actual worker finish/replay.
 execFileSync('docker',['exec',process.env.LIKERTS_WEBHOOK_TEST_CONTAINER,'psql','-U','postgres','-v','ON_ERROR_STOP=1','-c',`update likerts.webhook_deliveries set status='failed',failure_code='http_permanent' where id='${delivery.id}'`],{stdio:'pipe'});
 const replay=await call('webhook_deliveries_replay',{id:delivery.id,idempotencyKey:'replay'});assert.equal(replay.replayCount,1);assert.equal(replay.eventId,delivery.eventId);
 cli('webhook_endpoints_update',{id:created.endpoint.id,revoke:true});assert.equal(cli('webhook_deliveries_get',{id:delivery.id}).status,'cancelled');
 const revoked=await request('/v1/webhook-endpoints','POST',{idempotencyKey:'endpoint',url:'https://hooks.customer.com/likerts'});assert.equal(revoked.status,410);assert.equal((await revoked.json()).error.code,'webhook_revoked');
 console.log('Webhook API/MCP/CLI PostgreSQL PASS: typed credentials and scopes, workspace isolation, one response event for eight retries, rotation, replay, revocation, and structured errors.');
}finally{await mcp?.close();await server?.close();child.kill('SIGTERM');await new Promise(r=>child.exitCode!==null?r():child.once('exit',r));}
