{
  "formatVersion": "1.1",
  "component": {
    "group": "com.likerts",
    "module": "likerts-android",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "likerts-android-0.0.3.aar",
          "url": "likerts-android-0.0.3.aar",
          "size": 227428,
          "sha512": "42b7d35a3936670f82e8e3b62989c6a30c2f961e90cf962dc6706fdfd3e3562c9acdbc30ba3f6f729e8cc555d8975cd53a5c02e73703584d1310393f54ff29e3",
          "sha256": "664410291dda37279e6f776df0503c92d71365c0d0a65aa2e54ef4473744a80d",
          "sha1": "69d20e8a499d3a64b6c1ef1e4c98141d800f85b8",
          "md5": "bb85c16c7a13cb8fc69915b31473bf1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "likerts-android-0.0.3.aar",
          "url": "likerts-android-0.0.3.aar",
          "size": 227428,
          "sha512": "42b7d35a3936670f82e8e3b62989c6a30c2f961e90cf962dc6706fdfd3e3562c9acdbc30ba3f6f729e8cc555d8975cd53a5c02e73703584d1310393f54ff29e3",
          "sha256": "664410291dda37279e6f776df0503c92d71365c0d0a65aa2e54ef4473744a80d",
          "sha1": "69d20e8a499d3a64b6c1ef1e4c98141d800f85b8",
          "md5": "bb85c16c7a13cb8fc69915b31473bf1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "likerts-android-0.0.3-sources.jar",
          "url": "likerts-android-0.0.3-sources.jar",
          "size": 13783,
          "sha512": "690d320b4d1ee6cb8ff25ee88791a648d4f5821e490f89210557bce47a2c7bd2ce6389acb177ba3d72af7352d4f327b2536bb06e2001fc19204d002d4bd0b596",
          "sha256": "b398938b4741b53856fe1f763902a0eb2f03b2b59cb1db14738f000b09f0a93d",
          "sha1": "80e6ef03a71bb33cd1ac30cbb8883f73b2cb7229",
          "md5": "0fc22dfc263a2377fe0947101e57e51b"
        }
      ]
    }
  ]
}
