require_relative '../../node_modules/react-native/scripts/react_native_pods'
platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'LikertsRNAcceptance' do
  use_react_native!(
    :path => '../../node_modules/react-native',
    :app_path => File.expand_path('../..', __dir__)
  )
  post_install do |installer|
    react_native_post_install(installer, '../../node_modules/react-native', :mac_catalyst_enabled => false)
  end
end
