package com.likerts.sdk
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.util.UUID

data class OfflineLimits(val maxRecords:Int=1000,val maxBytes:Int=10*1024*1024,val maxAgeSeconds:Long=7*86400){init{require(maxRecords in 1..10000&&maxBytes in 1..100*1024*1024&&maxAgeSeconds in 1..30*86400)}}
enum class OfflineReason{invalid,conflict,unauthorized,revoked,deleted,expired}
data class OfflineStatus(val pending:Int,val blockedByReason:Map<OfflineReason,Int>,val expiredLocal:Int,val quarantined:Int,val bytes:Int)
data class OfflineAttempt(val status:Int,val responseId:String?=null,val receiptCollectionId:String?=null,val accepted:Boolean=false,val retryAfterSeconds:Int?=null)
data class OfflineOutcome(val recordId:String,val outcome:String,val reason:OfflineReason?=null,val retryAfterSeconds:Int?=null)
data class OfflineFlushReport(val attempted:Int,val accepted:Int,val cancelled:Boolean,val outcomes:List<OfflineOutcome>,val status:OfflineStatus)
interface OfflineSecureAdapter{val protectionProfile:String;suspend fun load():List<ByteArray>;suspend fun replace(records:List<ByteArray>);suspend fun seal(clear:ByteArray):ByteArray;suspend fun open(sealed:ByteArray):ByteArray}
@Serializable private data class Envelope(val id:String,val collectionId:String,val submission:ByteArray,val idempotencyKey:String,val createdAtMillis:Long,val byteSize:Int,var attemptCount:Int=0,var state:String="pending",var reason:String?=null)
class OfflineQueue(private val adapter:OfflineSecureAdapter,private val limits:OfflineLimits=OfflineLimits(),private val now:()->Long=System::currentTimeMillis){private val mutex=Mutex();private var flushing=false;init{require(adapter.protectionProfile=="android_keystore_aes_gcm"){"Android Keystore AES-GCM adapter required"}}
 private suspend fun read():Pair<MutableList<Envelope>,MutableList<ByteArray>>{val good=mutableListOf<Envelope>();val bad=mutableListOf<ByteArray>();adapter.load().forEach{try{good+=Json.decodeFromString<Envelope>(adapter.open(it).decodeToString())}catch(_:Throwable){bad+=it}};return good to bad}
 private suspend fun write(good:List<Envelope>,bad:List<ByteArray>){adapter.replace(bad+good.map{adapter.seal(Json.encodeToString(it).encodeToByteArray())})}
 suspend fun enqueue(collectionId:String,submission:ByteArray,idempotencyKey:String):String=mutex.withLock{require(collectionId.isNotBlank()&&idempotencyKey.isNotBlank());if(submission.size>65536)throw IllegalArgumentException("record exceeds 64 KiB");val(good,bad)=read();good.find{it.idempotencyKey==idempotencyKey}?.let{if(it.collectionId!=collectionId||!it.submission.contentEquals(submission))throw IllegalStateException("idempotency conflict");return@withLock it.id};if(good.size>=limits.maxRecords||good.sumOf{it.byteSize}+submission.size>limits.maxBytes)throw IllegalStateException("capacity exceeded");val value=Envelope(UUID.randomUUID().toString(),collectionId,submission.copyOf(),idempotencyKey,now(),submission.size);write(good+value,bad);value.id}
 suspend fun snapshot():OfflineStatus=mutex.withLock{snapshotUnlocked()}
 private suspend fun snapshotUnlocked():OfflineStatus{val(good,bad)=read();return OfflineStatus(good.count{it.state=="pending"},good.filter{it.state=="blocked"}.mapNotNull{it.reason?.let(OfflineReason::valueOf)}.groupingBy{it}.eachCount(),good.count{it.state=="expired_local"},bad.size,good.sumOf{it.byteSize})}
 suspend fun delete(id:String)=mutex.withLock{val(good,bad)=read();write(good.filter{it.id!=id},bad)}
 suspend fun deleteCollection(id:String):Int=mutex.withLock{val(good,bad)=read();val kept=good.filter{it.collectionId!=id};write(kept,bad);good.size-kept.size}
 suspend fun purgeQuarantined():Int=mutex.withLock{val(good,bad)=read();write(good,emptyList());bad.size}
 suspend fun flush(cancelled:()->Boolean={false},credential:suspend(String)->String?,send:suspend(String,String,ByteArray)->OfflineAttempt):OfflineFlushReport{mutex.withLock{if(flushing)throw IllegalStateException("flush active");flushing=true};var attempted=0;var accepted=0;var stopped=false;val outcomes=mutableListOf<OfflineOutcome>();try{val ids=mutex.withLock{val(good,bad)=read();var changed=false;good.filter{it.state!="expired_local"&&now()-it.createdAtMillis>limits.maxAgeSeconds*1000}.forEach{it.state="expired_local";it.reason=null;changed=true};if(changed)write(good,bad);good.filter{it.state=="pending"}.sortedWith(compareBy<Envelope>{it.createdAtMillis}.thenBy{it.id}).map{it.id}};for(id in ids){if(cancelled()){stopped=true;break};val candidate=mutex.withLock{read().first.find{it.id==id&&it.state=="pending"}}?:continue;val token=credential(candidate.collectionId);if(token==null){outcomes+=OfflineOutcome(id,"credential_unavailable");continue};attempted++;val attempt=try{send(candidate.collectionId,token,candidate.submission.copyOf())}catch(_:Throwable){OfflineAttempt(0)};mutex.withLock{val(good,bad)=read();val index=good.indexOfFirst{it.id==id};if(index<0)return@withLock;if(attempt.status in 200..299&&attempt.accepted&&attempt.receiptCollectionId==good[index].collectionId&&!attempt.responseId.isNullOrEmpty()){good.removeAt(index);accepted++;outcomes+=OfflineOutcome(id,"accepted")}else{good[index].attemptCount++;val retry=attempt.status in listOf(408,425,429)||attempt.status>=500||attempt.status==0;val reason=mapOf(400 to OfflineReason.invalid,409 to OfflineReason.conflict,401 to OfflineReason.unauthorized,403 to OfflineReason.revoked,404 to OfflineReason.deleted,410 to OfflineReason.expired)[attempt.status]?:if(attempt.status in 400..499&&!retry)OfflineReason.invalid else null;if(reason!=null){good[index].state="blocked";good[index].reason=reason.name;outcomes+=OfflineOutcome(id,"blocked",reason)}else{outcomes+=OfflineOutcome(id,"retry",retryAfterSeconds=if(retry)attempt.retryAfterSeconds?.coerceIn(0,86400)else null)}};write(good,bad)}}}finally{mutex.withLock{flushing=false}};return OfflineFlushReport(attempted,accepted,stopped,outcomes,snapshot())}
}
