import type {Receipt,Submission} from './index';

export type OfflineReason='invalid'|'conflict'|'unauthorized'|'revoked'|'deleted'|'expired';
export type OfflineState='pending'|'blocked'|'expired_local';
export interface OfflineLimits{maxRecords:number;maxBytes:number;maxAgeSeconds:number}
export interface OfflineStatus{pending:number;blockedByReason:Partial<Record<OfflineReason,number>>;expiredLocal:number;quarantined:number;bytes:number}
export interface OfflineOutcome{recordId:string;outcome:'accepted'|'retry'|'blocked'|'expired_local'|'quarantined'|'credential_unavailable';reason?:OfflineReason;retryAfterSeconds?:number}
export interface FlushReport{attempted:number;accepted:number;pending:number;blocked:number;expiredLocal:number;quarantined:number;cancelled:boolean;outcomes:OfflineOutcome[]}
export interface OpaqueQueueStore{load():Promise<Uint8Array[]>;replace(records:readonly Uint8Array[]):Promise<void>}
export interface QueueCipher{seal(cleartext:Uint8Array):Promise<Uint8Array>;open(ciphertext:Uint8Array):Promise<Uint8Array>}
export interface OfflineSendResult{status:number;receipt?:Receipt;retryAfterSeconds?:number}
export type OfflineSender=(collectionId:string,credential:string,submission:Submission,signal?:AbortSignal)=>Promise<OfflineSendResult>;
type RecordData={id:string;collectionId:string;submissionText:string;createdAt:number;byteSize:number;attemptCount:number;state:OfflineState;reason?:OfflineReason};
const DEFAULTS:OfflineLimits={maxRecords:1000,maxBytes:10*1024*1024,maxAgeSeconds:7*86400},HARD={maxRecords:10000,maxBytes:100*1024*1024,maxAgeSeconds:30*86400},MAX_RECORD=65536;
const encoder=new TextEncoder(),decoder=new TextDecoder();
const canonical=(value:unknown):string=>JSON.stringify(value&&typeof value==='object'&&!Array.isArray(value)?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,JSON.parse(canonical(v))])):Array.isArray(value)?value.map(v=>JSON.parse(canonical(v))):value);
const reason=(status:number):OfflineReason|undefined=>({400:'invalid',409:'conflict',401:'unauthorized',403:'revoked',404:'deleted',410:'expired'} as Record<number,OfflineReason>)[status]??(status>=400&&status<500&&![408,425,429].includes(status)?'invalid':undefined);
const retryable=(status:number)=>[408,425,429].includes(status)||status>=500;
const limits=(value:Partial<OfflineLimits>):OfflineLimits=>{const result={...DEFAULTS,...value};if(!Number.isSafeInteger(result.maxRecords)||result.maxRecords<1||result.maxRecords>HARD.maxRecords||!Number.isSafeInteger(result.maxBytes)||result.maxBytes<1||result.maxBytes>HARD.maxBytes||!Number.isSafeInteger(result.maxAgeSeconds)||result.maxAgeSeconds<1||result.maxAgeSeconds>HARD.maxAgeSeconds)throw new RangeError('Offline queue limits exceed hard bounds');return result};

export interface NativeOfflineAdapter extends OpaqueQueueStore,QueueCipher { readonly secureKeyProfile:'keychain'|'android_keystore'; readonly encryptedStorage:true;createRecordId():string }
export function openNativeOfflineQueue(adapter:NativeOfflineAdapter,sender:OfflineSender,configuration:Partial<OfflineLimits>={}):OfflineQueue{if(adapter.encryptedStorage!==true||!['keychain','android_keystore'].includes(adapter.secureKeyProfile))throw new Error('A native encrypted storage and secure key adapter is required');return new OfflineQueue(adapter,adapter,sender,configuration,undefined,()=>adapter.createRecordId())}

export class OfflineQueue{
 private readonly configuration:OfflineLimits;private flushing=false;
 constructor(private store:OpaqueQueueStore,private cipher:QueueCipher,private sender:OfflineSender,configuration:Partial<OfflineLimits>={},private now:()=>number=()=>Date.now(),private randomId:()=>string=()=>{throw new Error('A native secure random record ID adapter is required')}){this.configuration=limits(configuration)}
 private async read(){const good:{record:RecordData;ciphertext:Uint8Array}[]=[],bad:Uint8Array[]=[];for(const ciphertext of await this.store.load()){try{good.push({record:JSON.parse(decoder.decode(await this.cipher.open(ciphertext))),ciphertext})}catch{bad.push(ciphertext)}}return{good,bad}}
 private async write(records:RecordData[],bad:Uint8Array[]){await this.store.replace([...bad,...await Promise.all(records.map(r=>this.cipher.seal(encoder.encode(canonical(r)))) )])}
 async enqueue(collectionId:string,submission:Submission){if(!collectionId||!submission.idempotencyKey)throw new TypeError('collectionId and idempotencyKey are required');const submissionText=canonical(submission),byteSize=encoder.encode(submissionText).byteLength;if(byteSize>MAX_RECORD)throw new RangeError('Offline record exceeds 64 KiB');const {good,bad}=await this.read(),records=good.map(v=>v.record),prior=records.find(r=>JSON.parse(r.submissionText).idempotencyKey===submission.idempotencyKey);if(prior){if(prior.collectionId!==collectionId||prior.submissionText!==submissionText)throw new Error('Offline idempotency conflict');return prior.id}if(records.length>=this.configuration.maxRecords||records.reduce((sum,r)=>sum+r.byteSize,0)+byteSize>this.configuration.maxBytes)throw new RangeError('Offline queue capacity exceeded');const record={id:this.randomId(),collectionId,submissionText,createdAt:this.now(),byteSize,attemptCount:0,state:'pending' as const};await this.write([...records,record],bad);return record.id}
 async snapshot():Promise<OfflineStatus>{const {good,bad}=await this.read(),status:OfflineStatus={pending:0,blockedByReason:{},expiredLocal:0,quarantined:bad.length,bytes:0};for(const {record:r} of good){status.bytes+=r.byteSize;if(r.state==='pending')status.pending++;else if(r.state==='expired_local')status.expiredLocal++;else if(r.reason)status.blockedByReason[r.reason]=(status.blockedByReason[r.reason]??0)+1}return status}
 async delete(recordId:string){const {good,bad}=await this.read();await this.write(good.map(v=>v.record).filter(r=>r.id!==recordId),bad)}
 async deleteCollection(collectionId:string){const {good,bad}=await this.read(),kept=good.map(v=>v.record).filter(r=>r.collectionId!==collectionId);const count=good.length-kept.length;await this.write(kept,bad);return count}
 async purgeQuarantined(){const {good,bad}=await this.read();await this.write(good.map(v=>v.record),[]);return bad.length}
 async flush(resolveCredential:(collectionId:string)=>Promise<string|undefined>,signal?:AbortSignal):Promise<FlushReport>{if(this.flushing)throw new Error('Offline flush already active');this.flushing=true;const report:FlushReport={attempted:0,accepted:0,pending:0,blocked:0,expiredLocal:0,quarantined:0,cancelled:false,outcomes:[]};try{const initial=await this.read(),initialRecords=initial.good.map(v=>v.record);let expiredChanged=false;for(const record of initialRecords){if(record.state!=='expired_local'&&this.now()-record.createdAt>this.configuration.maxAgeSeconds*1000){record.state='expired_local';delete record.reason;expiredChanged=true}}if(expiredChanged)await this.write(initialRecords,initial.bad);const ids=initialRecords.filter(r=>r.state==='pending').sort((a,b)=>a.createdAt-b.createdAt||a.id.localeCompare(b.id)).map(r=>r.id);for(const id of ids){if(signal?.aborted){report.cancelled=true;break}const current=await this.read(),records=current.good.map(v=>v.record),record=records.find(r=>r.id===id);if(!record||record.state!=='pending')continue;const credential=await resolveCredential(record.collectionId);if(!credential){report.pending++;report.outcomes.push({recordId:id,outcome:'credential_unavailable'});continue}report.attempted++;let result:OfflineSendResult|undefined;try{result=await this.sender(record.collectionId,credential,JSON.parse(record.submissionText),signal)}catch{}const fresh=await this.read(),updated=fresh.good.map(v=>v.record),target=updated.find(r=>r.id===id);if(!target)continue;const receipt=result?.receipt;if(result&&result.status>=200&&result.status<300&&receipt?.accepted===true&&receipt.collectionId===target.collectionId&&receipt.responseId.length>0){await this.write(updated.filter(r=>r.id!==id),fresh.bad);report.accepted++;report.outcomes.push({recordId:id,outcome:'accepted'});continue}target.attemptCount++;const terminal=result&&reason(result.status);if(terminal){target.state='blocked';target.reason=terminal;report.blocked++;report.outcomes.push({recordId:id,outcome:'blocked',reason:terminal})}else{report.pending++;report.outcomes.push({recordId:id,outcome:'retry',...(result?.retryAfterSeconds!==undefined&&retryable(result.status)?{retryAfterSeconds:Math.max(0,Math.min(86400,Math.floor(result.retryAfterSeconds)))}:{})})}await this.write(updated,fresh.bad)}}finally{this.flushing=false}const final=await this.snapshot();report.pending=final.pending;report.quarantined=final.quarantined;report.expiredLocal=final.expiredLocal;report.blocked=Object.values(final.blockedByReason).reduce((a,b)=>a+(b??0),0);return report}
}
