import {selectedChoices, otherTexts, toggleChoice, setOtherText, choiceError} from './choice-features';
import React, {useEffect, useState} from 'react';
import {AccessibilityInfo, Pressable, StyleProp, Text, TextInput, TextStyle, View, ViewStyle} from 'react-native';
import {visibleAnswers,visibleQuestionIds} from './index';
import {pageRoute,routedAnswers} from './branching';
import {advancedAnswerError,allocationRemaining,moveRanking,rankingOrder,setAllocation,setMatrixChoice} from './advanced-questions';
import type {Answer, Collection} from './index';

export interface SurveyMessages {requiredSuffix:string;requiredError:string;selectionRangeError:string;selectionLimitHint:string;datePlaceholder:string;back:string;next:string;progress:string;submit:string;submitting:string;selectPlaceholder:string;otherError:string;moveUp:string;moveDown:string;remaining:string;advancedError:string}
export interface SurveyStyles {container?:StyleProp<ViewStyle>;title?:StyleProp<TextStyle>;question?:StyleProp<ViewStyle>;label?:StyleProp<TextStyle>;choice?:StyleProp<ViewStyle>;choiceText?:StyleProp<TextStyle>;input?:StyleProp<TextStyle>;error?:StyleProp<TextStyle>;submit?:StyleProp<ViewStyle>;submitText?:StyleProp<TextStyle>}
export interface SurveyProps {collection:Collection;onSubmit:(answers:Record<string,Answer>)=>void;disabled?:boolean;submitting?:boolean;initialAnswers?:Record<string,Answer>;onAnswersChange?:(answers:Record<string,Answer>)=>void;onValidationError?:(message:string)=>void;messages?:Partial<SurveyMessages>;styles?:SurveyStyles;testID?:string}

const defaults:SurveyMessages={requiredSuffix:'required',requiredError:'{question}: an answer is required.',selectionRangeError:'{question}: select between {min} and {max} options.',selectionLimitHint:'Maximum selections reached',datePlaceholder:'YYYY-MM-DD',back:'Back',next:'Next',progress:'Page {current} of {total}',submit:'Submit',submitting:'Submitting…',selectPlaceholder:'Select an answer',otherError:'{question}: enter valid text for the selected Other option.',moveUp:'Move up',moveDown:'Move down',remaining:'{remaining} remaining',advancedError:'{question}: complete the answer.'};
const format=(template:string,values:Record<string,string|number>)=>Object.entries(values).reduce((result,[key,value])=>result.replace(`{${key}}`,String(value)),template);

/** Host owns network lifecycle, placement and dismissal; renderer checks selection bounds. */
export function Survey({collection,onSubmit,disabled=false,submitting=false,initialAnswers={},onAnswersChange,onValidationError,messages:overrides,styles={},testID='likerts-survey'}:SurveyProps) {
  const messages={...defaults};for(const key of Object.keys(defaults) as (keyof SurveyMessages)[]){const value=overrides?.[key];if(typeof value==='string')messages[key]=value}const blocked=disabled||submitting;
  const pages=collection.schema.pages??[{id:'survey',questionIds:collection.schema.questions.map(q=>q.id)}];
  const [answers,setAnswers]=useState<Record<string,Answer>>(()=>routedAnswers(collection.schema,{...initialAnswers}));const [error,setError]=useState('');const [openDropdowns,setOpenDropdowns]=useState<Record<string,boolean>>({});const [currentPage,setCurrentPage]=useState(0);const [history,setHistory]=useState([0]);
  if (![1,2,3,4,5].includes(collection.schema.schemaVersion)) throw new Error('Unsupported survey schema version');
  useEffect(()=>{const reset=routedAnswers(collection.schema,{...initialAnswers});setAnswers(reset);setCurrentPage(0);setHistory([0]);setOpenDropdowns({});setError('');onAnswersChange?.(reset);},[collection.id,collection.version]);
  useEffect(()=>{if(error)AccessibilityInfo.announceForAccessibility(error);},[error]);
  const update=(id:string,value:Answer|((current:Answer|undefined)=>Answer))=>{setAnswers(previous=>{const next=routedAnswers(collection.schema,{...previous,[id]:typeof value==='function'?value(previous[id]):value});const route=pageRoute(collection.schema,next);if(!route.includes(currentPage)){let shared=route[0]??0;for(let i=0;i<Math.min(history.length,route.length)&&history[i]===route[i];i++)shared=route[i];setCurrentPage(shared);setHistory(route.slice(0,route.indexOf(shared)+1));}onAnswersChange?.(next);return next});setError('')};
  const fail=(message:string)=>{setError(message);onValidationError?.(message)};
  const visible=visibleQuestionIds(collection.schema.questions,answers),currentQuestions=new Set(pages[currentPage]?.questionIds??[]),route=pageRoute(collection.schema,answers),routeIndex=route.indexOf(currentPage);
  const advance=()=>{const result:Record<string,Answer>={};for(const q of collection.schema.questions){if(!visible.has(q.id)||!currentQuestions.has(q.id))continue;const value=answers[q.id];if(q.type==='ranking'||q.type==='matrix'||q.type==='constant_sum'){const code=advancedAnswerError(q,value);if(code){fail(format(code==='required'?messages.requiredError:messages.advancedError,{question:q.label}));return}if(value!==undefined)result[q.id]=value;continue}const isChoice=q.type==='single_choice'||q.type==='multiple_choice';if(value===undefined||value===''||(isChoice&&selectedChoices(value).length===0)||(Array.isArray(value)&&value.length===0)){if(q.required){fail(format(messages.requiredError,{question:q.label}));return}continue}if(isChoice){const code=choiceError(q,value);if(code){fail(format(code==='other'?messages.otherError:messages.selectionRangeError,{question:q.label,min:Math.max(q.required?1:0,q.minSelections??0),max:q.maxSelections??q.options?.length??0}));return}}result[q.id]=q.type==='number'||q.type==='scale'?Number(value):value}if(routeIndex+1<route.length){const next=route[routeIndex+1];setCurrentPage(next);setHistory(route.slice(0,routeIndex+2));return}onSubmit(routedAnswers(collection.schema,{...answers,...result}))};
  return <View style={styles.container} testID={testID} accessibilityLabel={collection.schema.title}>
    <Text style={styles.title} accessibilityRole="header" testID={`${testID}-title`}>{collection.schema.title}</Text>
    {collection.schema.pages?<Text testID={`${testID}-progress`}>{format(messages.progress,{current:currentPage+1,total:pages.length})}</Text>:null}
    {collection.schema.questions.filter(q=>visible.has(q.id)&&currentQuestions.has(q.id)).map(q=>{
      const labelId=`${testID}-${q.id}-label`;const questionLabel=`${q.label}${q.required?`, ${messages.requiredSuffix}`:''}`;
      return <View key={q.id} style={styles.question} testID={`${testID}-question-${q.id}`}>
        <Text style={styles.label} nativeID={labelId}>{q.label}{q.required?` (${messages.requiredSuffix})`:''}</Text>
        {q.type==='ranking'?rankingOrder(q,answers[q.id]).map((id,index)=>{const option=q.options?.find(value=>value.id===id)!;return <View key={id}><Text style={styles.choiceText}>{index+1}. {option.label}</Text><Pressable testID={`${testID}-${q.id}-${id}-up`} accessibilityRole="button" accessibilityLabel={`${messages.moveUp}: ${option.label}`} disabled={blocked||index===0} onPress={()=>update(q.id,current=>moveRanking(q,current,id,-1))}><Text>{messages.moveUp}</Text></Pressable><Pressable testID={`${testID}-${q.id}-${id}-down`} accessibilityRole="button" accessibilityLabel={`${messages.moveDown}: ${option.label}`} disabled={blocked||index===rankingOrder(q,answers[q.id]).length-1} onPress={()=>update(q.id,current=>moveRanking(q,current,id,1))}><Text>{messages.moveDown}</Text></Pressable></View>})
        :q.type==='matrix'?(q.rows??[]).map(row=><View key={row.id}><Text style={styles.choiceText}>{row.label}</Text>{(q.columns??[]).map(column=>{const value=(answers[q.id] as Record<string,string|string[]>|undefined)?.[row.id],selected=Array.isArray(value)?value.includes(column.id):value===column.id;return <Pressable key={column.id} testID={`${testID}-${q.id}-${row.id}-${column.id}`} accessibilityRole={q.matrixMode==='single'?'radio':'checkbox'} accessibilityLabel={`${row.label}: ${column.label}`} accessibilityState={{checked:selected,disabled:blocked}} disabled={blocked} onPress={()=>update(q.id,current=>setMatrixChoice(q,current,row.id,column.id))}><Text>{selected?'✓ ':''}{column.label}</Text></Pressable>})}</View>)
        :q.type==='constant_sum'?<>{(q.items??[]).map(item=><TextInput key={item.id} style={styles.input} testID={`${testID}-${q.id}-${item.id}`} accessibilityLabel={`${q.label}: ${item.label}`} keyboardType="number-pad" editable={!blocked} value={String((answers[q.id] as Record<string,number>|undefined)?.[item.id]??'')} onChangeText={value=>update(q.id,current=>setAllocation(current,item.id,Number(value)))}/>)}<Text accessibilityLiveRegion="polite" testID={`${testID}-${q.id}-remaining`}>{format(messages.remaining,{remaining:allocationRemaining(q,answers[q.id])})}</Text></>
        :<>{q.presentation==='dropdown'?<Pressable style={styles.choice} testID={`${testID}-${q.id}-dropdown`} accessibilityRole="button" accessibilityLabel={`${q.label}: ${q.options?.find(o=>o.id===selectedChoices(answers[q.id])[0])?.label??messages.selectPlaceholder}`} accessibilityState={{expanded:!!openDropdowns[q.id],disabled:blocked}} disabled={blocked} onPress={()=>setOpenDropdowns(previous=>({...previous,[q.id]:!previous[q.id]}))}><Text style={styles.choiceText}>{q.options?.find(o=>o.id===selectedChoices(answers[q.id])[0])?.label??messages.selectPlaceholder}</Text></Pressable>:null}
        {q.type==='single_choice'||q.type==='multiple_choice'?(q.presentation==='dropdown'&&!openDropdowns[q.id]?[]:q.options??[]).map(option=>{
          const current=selectedChoices(answers[q.id]),selected=current.includes(option.id);const exclusive=current.some(id=>q.options?.some(o=>o.id===id&&o.exclusive));
          const atLimit=q.type==='multiple_choice'&&!selected&&!option.exclusive&&!exclusive&&q.maxSelections!==undefined&&current.length>=q.maxSelections;const optionBlocked=blocked||atLimit;
          return <Pressable key={option.id} style={styles.choice} testID={`${testID}-${q.id}-${option.id}`} disabled={optionBlocked} accessibilityLabel={`${q.label}: ${option.label}`} accessibilityHint={atLimit?messages.selectionLimitHint:undefined} accessibilityRole={q.type==='single_choice'?'radio':'checkbox'} accessibilityState={{checked:selected,disabled:optionBlocked}} onPress={()=>{if(!optionBlocked){update(q.id,current=>toggleChoice(q,current,option.id));if(q.presentation==='dropdown')setOpenDropdowns(previous=>({...previous,[q.id]:false}));}}}><Text style={styles.choiceText}>{selected?'✓ ':''}{option.label}</Text></Pressable>;
        })
        :q.type==='scale'&&(q.labels!==undefined||q.preset==='nps'||q.presentation==='stars')?Array.from({length:(q.max??0)-(q.min??0)+1},(_,i)=>(q.min??0)+i).map(value=>{const label=q.labels?.[String(value)]?`${value} — ${q.labels[String(value)]}`:String(value);return <Pressable key={value} style={styles.choice} testID={`${testID}-${q.id}-${value}`} disabled={blocked} accessibilityLabel={`${q.label}: ${label}`} accessibilityRole="radio" accessibilityState={{checked:answers[q.id]===value,disabled:blocked}} onPress={()=>{if(!blocked)update(q.id,value)}}><Text style={styles.choiceText}>{q.presentation==='stars'?'★'.repeat(value):label}</Text></Pressable>})
        :<TextInput style={styles.input} testID={`${testID}-${q.id}`} accessibilityLabel={questionLabel} accessibilityLabelledBy={labelId} editable={!blocked} value={String(answers[q.id]??'')} multiline={q.type==='text'} maxLength={q.maxLength} placeholder={q.type==='date'?messages.datePlaceholder:undefined} keyboardType={q.type==='number'||q.type==='scale'?'numbers-and-punctuation':'default'} onChangeText={value=>update(q.id,value)}/>}</>}
        {(q.options??[]).filter(o=>o.other!==undefined&&selectedChoices(answers[q.id]).includes(o.id)).map(option=><TextInput key={option.id} style={styles.input} testID={`${testID}-${q.id}-${option.id}-text`} accessibilityLabel={`${q.label}: ${option.label}`} editable={!blocked} value={otherTexts(answers[q.id])[option.id]??''} onChangeText={value=>update(q.id,current=>setOtherText(q,current,option.id,value))}/>)}

      </View>})}
    {error?<Text style={styles.error} testID={`${testID}-error`} accessibilityRole="alert" accessibilityLiveRegion="assertive">{error}</Text>:null}
    {collection.schema.pages&&history.length>1?<Pressable style={styles.submit} testID={`${testID}-back`} disabled={blocked} accessibilityRole="button" onPress={()=>{if(!blocked){const next=history.slice(0,-1);setHistory(next);setCurrentPage(next[next.length-1]);setError('')}}}><Text style={styles.submitText}>{messages.back}</Text></Pressable>:null}
    <Pressable style={styles.submit} testID={`${testID}-${routeIndex+1<route.length?'next':'submit'}`} disabled={blocked} accessibilityLabel={submitting?messages.submitting:routeIndex+1<route.length?messages.next:messages.submit} accessibilityRole="button" accessibilityState={{disabled:blocked,busy:submitting}} onPress={()=>{if(!blocked)advance()}}><Text style={styles.submitText}>{submitting?messages.submitting:routeIndex+1<route.length?messages.next:messages.submit}</Text></Pressable>
  </View>;
}
