import { createContext, useContext, useMemo } from 'react';

export const languageOptions = [
  { value: 'en-US', label: 'English', nativeLabel: 'English', dir: 'ltr' },
  { value: 'es-ES', label: 'Spanish', nativeLabel: 'Español', dir: 'ltr' },
  { value: 'pt-BR', label: 'Portuguese', nativeLabel: 'Português', dir: 'ltr' },
  { value: 'fr-FR', label: 'French', nativeLabel: 'Français', dir: 'ltr' },
  { value: 'de-DE', label: 'German', nativeLabel: 'Deutsch', dir: 'ltr' },
  { value: 'zh-CN', label: 'Chinese', nativeLabel: '简体中文', dir: 'ltr' },
  { value: 'ja-JP', label: 'Japanese', nativeLabel: '日本語', dir: 'ltr' },
  { value: 'ko-KR', label: 'Korean', nativeLabel: '한국어', dir: 'ltr' },
  { value: 'ar-SA', label: 'Arabic', nativeLabel: 'العربية', dir: 'rtl' },
  { value: 'hi-IN', label: 'Hindi', nativeLabel: 'हिन्दी', dir: 'ltr' },
];

const en = {
  free: 'Free to use · no account required', ad: 'Advertisement', adReserved: 'Reserved ad inventory',
  hero: 'Free synthetic market research, grounded in current sources', subhero: 'Test concepts and audience hypotheses with market-aware evidence, explicit assumptions, and multi-model review—no account required.',
  question: 'Research question', audience: 'Audience', audiencePlaceholder: 'e.g. Remote knowledge workers · Ages 25–54', market: 'Market', global: 'Global',
  reportLanguage: 'Report language', sourceLanguage: 'Source language', anyLanguage: 'Any language', units: 'Simulation units', notPeople: 'not surveyed people',
  sources: 'Evidence sources', optionalUrls: 'optional public URLs', addSource: 'Add source', removeSource: 'Remove source', run: 'Run grounded study', running: 'Running research agents…',
  assumptions: 'Assumptions', assumptionsLabel: 'Assumptions the models may use', assumptionsNote: 'Unsupported assumptions are labeled in the evidence ledger.',
  readySources: 'Ready with {sources} supplied source(s) and {assumptions} assumption(s).',
  autoEvidence: 'Likerts will run two bounded web searches through Vercel AI Gateway and disclose retrieved sources. If retrieval fails, the run is labeled prior-only.',
  progress: 'Research run progress', frame: 'Frame', search: 'Search', simulate: 'Simulate', review: 'Review', complete: 'Complete', fallback: 'Fallback used', inProgress: 'In progress', queued: 'Queued', runLabel: 'Run', notStarted: 'not started', copyRun: 'Copy run ID',
  overview: 'Overview', segments: 'Segments', verbatims: 'Verbatims', evidence: 'Evidence', method: 'Method', export: 'Export evidence pack', replay: 'Replay',
  likely: 'likely', unlikely: 'unlikely', unsure: 'unsure', hypothesis: 'Treat this as a hypothesis to test, not a market estimate.', suggest: 'What the models suggest', changeRead: 'What would change this read',
  ledger: 'Research ledger', coverage: 'Evidence coverage', populationFit: 'Population fit', independentReview: 'Independent review', inspectEvidence: 'Inspect evidence', marketLabel: 'Market', outputLabel: 'Report',
  directional: 'Directional synthetic estimate — not observed human evidence.', methodological: 'methodological confidence',
};

const dictionaries = {
  'en-US': en,
  'es-ES': {
    free: 'Gratis · sin cuenta', ad: 'Publicidad', adReserved: 'Espacio publicitario reservado', hero: 'Crea un estudio sintético defendible', subhero: 'Fundamenta un panel direccional en fuentes actuales, supuestos de población y revisión independiente de modelos.', question: 'Pregunta de investigación', audience: 'Audiencia', audiencePlaceholder: 'p. ej., profesionales remotos · 25–54 años', market: 'Mercado', global: 'Global', reportLanguage: 'Idioma del informe', sourceLanguage: 'Idioma de las fuentes', anyLanguage: 'Cualquier idioma', units: 'Unidades de simulación', notPeople: 'no son personas encuestadas', sources: 'Fuentes de evidencia', optionalUrls: 'URL públicas opcionales', addSource: 'Añadir fuente', removeSource: 'Eliminar fuente', run: 'Ejecutar estudio fundamentado', running: 'Agentes investigando…', assumptions: 'Supuestos', assumptionsLabel: 'Supuestos que pueden usar los modelos', assumptionsNote: 'Los supuestos sin respaldo se identifican en el registro.', readySources: 'Listo con {sources} fuente(s) y {assumptions} supuesto(s).', autoEvidence: 'Likerts hará dos búsquedas web acotadas mediante Vercel AI Gateway y mostrará las fuentes recuperadas.', progress: 'Progreso del estudio', frame: 'Definir', search: 'Buscar', simulate: 'Simular', review: 'Revisar', complete: 'Completo', fallback: 'Se usó respaldo', inProgress: 'En curso', queued: 'En cola', runLabel: 'Ejecución', notStarted: 'sin iniciar', copyRun: 'Copiar ID', overview: 'Resumen', segments: 'Segmentos', verbatims: 'Respuestas', evidence: 'Evidencia', method: 'Método', export: 'Exportar evidencia', replay: 'Repetir', likely: 'probable', unlikely: 'improbable', unsure: 'duda', hypothesis: 'Trátalo como una hipótesis, no como una estimación de mercado.', suggest: 'Lo que sugieren los modelos', changeRead: 'Qué cambiaría esta lectura', ledger: 'Registro de investigación', coverage: 'Cobertura de evidencia', populationFit: 'Ajuste poblacional', independentReview: 'Revisión independiente', inspectEvidence: 'Ver evidencia', marketLabel: 'Mercado', outputLabel: 'Informe', directional: 'Estimación sintética direccional — no es evidencia humana observada.', methodological: 'confianza metodológica',
  },
  'pt-BR': {
    free: 'Grátis · sem conta', ad: 'Publicidade', adReserved: 'Espaço publicitário reservado', hero: 'Crie um estudo sintético defensável', subhero: 'Fundamente um painel direcional em fontes atuais, premissas populacionais e revisão independente de modelos.', question: 'Pergunta de pesquisa', audience: 'Público', audiencePlaceholder: 'ex.: profissionais remotos · 25–54 anos', market: 'Mercado', global: 'Global', reportLanguage: 'Idioma do relatório', sourceLanguage: 'Idioma das fontes', anyLanguage: 'Qualquer idioma', units: 'Unidades de simulação', notPeople: 'não são pessoas pesquisadas', sources: 'Fontes de evidência', optionalUrls: 'URLs públicas opcionais', addSource: 'Adicionar fonte', removeSource: 'Remover fonte', run: 'Executar estudo fundamentado', running: 'Agentes pesquisando…', assumptions: 'Premissas', assumptionsLabel: 'Premissas que os modelos podem usar', assumptionsNote: 'Premissas sem suporte são marcadas no registro.', readySources: 'Pronto com {sources} fonte(s) e {assumptions} premissa(s).', autoEvidence: 'O Likerts fará duas buscas web limitadas pelo Vercel AI Gateway e mostrará as fontes recuperadas.', progress: 'Progresso da pesquisa', frame: 'Definir', search: 'Buscar', simulate: 'Simular', review: 'Revisar', complete: 'Concluído', fallback: 'Fallback usado', inProgress: 'Em andamento', queued: 'Na fila', runLabel: 'Execução', notStarted: 'não iniciada', copyRun: 'Copiar ID', overview: 'Visão geral', segments: 'Segmentos', verbatims: 'Respostas', evidence: 'Evidência', method: 'Método', export: 'Exportar evidências', replay: 'Repetir', likely: 'provável', unlikely: 'improvável', unsure: 'incerto', hypothesis: 'Trate como hipótese a testar, não como estimativa de mercado.', suggest: 'O que os modelos sugerem', changeRead: 'O que mudaria esta leitura', ledger: 'Registro de pesquisa', coverage: 'Cobertura de evidência', populationFit: 'Adequação populacional', independentReview: 'Revisão independente', inspectEvidence: 'Ver evidência', marketLabel: 'Mercado', outputLabel: 'Relatório', directional: 'Estimativa sintética direcional — não é evidência humana observada.', methodological: 'confiança metodológica',
  },
  'fr-FR': {
    free: 'Gratuit · sans compte', ad: 'Publicité', adReserved: 'Emplacement publicitaire réservé', hero: 'Créez une étude synthétique défendable', subhero: 'Fondez un panel directionnel sur des sources actuelles, des hypothèses de population et une revue indépendante des modèles.', question: 'Question de recherche', audience: 'Audience', audiencePlaceholder: 'ex. télétravailleurs qualifiés · 25–54 ans', market: 'Marché', global: 'Monde', reportLanguage: 'Langue du rapport', sourceLanguage: 'Langue des sources', anyLanguage: 'Toutes les langues', units: 'Unités de simulation', notPeople: 'pas des personnes interrogées', sources: 'Sources de preuve', optionalUrls: 'URL publiques facultatives', addSource: 'Ajouter une source', removeSource: 'Supprimer la source', run: 'Lancer l’étude étayée', running: 'Agents de recherche en cours…', assumptions: 'Hypothèses', assumptionsLabel: 'Hypothèses utilisables par les modèles', assumptionsNote: 'Les hypothèses non étayées sont signalées dans le registre.', readySources: 'Prêt avec {sources} source(s) et {assumptions} hypothèse(s).', autoEvidence: 'Likerts effectuera deux recherches web ciblées via Vercel AI Gateway et indiquera chaque source.', progress: 'Progression de l’étude', frame: 'Cadrer', search: 'Chercher', simulate: 'Simuler', review: 'Réviser', complete: 'Terminé', fallback: 'Solution de repli', inProgress: 'En cours', queued: 'En attente', runLabel: 'Exécution', notStarted: 'non démarrée', copyRun: 'Copier l’ID', overview: 'Vue d’ensemble', segments: 'Segments', verbatims: 'Verbatims', evidence: 'Preuves', method: 'Méthode', export: 'Exporter les preuves', replay: 'Relancer', likely: 'probable', unlikely: 'improbable', unsure: 'incertain', hypothesis: 'Traitez ceci comme une hypothèse, pas comme une estimation de marché.', suggest: 'Ce que suggèrent les modèles', changeRead: 'Ce qui changerait cette lecture', ledger: 'Registre de recherche', coverage: 'Couverture des preuves', populationFit: 'Adéquation population', independentReview: 'Revue indépendante', inspectEvidence: 'Voir les preuves', marketLabel: 'Marché', outputLabel: 'Rapport', directional: 'Estimation synthétique directionnelle — aucune preuve humaine observée.', methodological: 'confiance méthodologique',
  },
  'de-DE': {
    free: 'Kostenlos · kein Konto', ad: 'Werbung', adReserved: 'Reservierte Werbefläche', hero: 'Erstelle eine belastbare synthetische Studie', subhero: 'Stütze ein richtungsweisendes Panel auf aktuelle Quellen, Populationsannahmen und unabhängige Modellprüfung.', question: 'Forschungsfrage', audience: 'Zielgruppe', audiencePlaceholder: 'z. B. Remote-Wissensarbeiter · 25–54 Jahre', market: 'Markt', global: 'Global', reportLanguage: 'Berichtssprache', sourceLanguage: 'Quellsprache', anyLanguage: 'Alle Sprachen', units: 'Simulationseinheiten', notPeople: 'keine befragten Personen', sources: 'Evidenzquellen', optionalUrls: 'optionale öffentliche URLs', addSource: 'Quelle hinzufügen', removeSource: 'Quelle entfernen', run: 'Fundierte Studie starten', running: 'Recherche-Agenten arbeiten…', assumptions: 'Annahmen', assumptionsLabel: 'Annahmen für die Modelle', assumptionsNote: 'Unbelegte Annahmen werden im Evidenzprotokoll markiert.', readySources: 'Bereit mit {sources} Quelle(n) und {assumptions} Annahme(n).', autoEvidence: 'Likerts führt zwei begrenzte Websuchen über Vercel AI Gateway aus und legt alle Quellen offen.', progress: 'Studienfortschritt', frame: 'Rahmen', search: 'Suche', simulate: 'Simulation', review: 'Prüfung', complete: 'Fertig', fallback: 'Fallback genutzt', inProgress: 'In Arbeit', queued: 'Wartend', runLabel: 'Lauf', notStarted: 'nicht gestartet', copyRun: 'Lauf-ID kopieren', overview: 'Überblick', segments: 'Segmente', verbatims: 'Antworten', evidence: 'Evidenz', method: 'Methode', export: 'Evidenz exportieren', replay: 'Wiederholen', likely: 'wahrscheinlich', unlikely: 'unwahrscheinlich', unsure: 'unsicher', hypothesis: 'Als zu testende Hypothese behandeln, nicht als Marktschätzung.', suggest: 'Was die Modelle nahelegen', changeRead: 'Was diese Einschätzung ändern würde', ledger: 'Forschungsprotokoll', coverage: 'Evidenzabdeckung', populationFit: 'Populationspassung', independentReview: 'Unabhängige Prüfung', inspectEvidence: 'Evidenz prüfen', marketLabel: 'Markt', outputLabel: 'Bericht', directional: 'Synthetische Richtungsschätzung — keine beobachtete menschliche Evidenz.', methodological: 'methodische Sicherheit',
  },
  'zh-CN': {
    free: '免费使用 · 无需账户', ad: '广告', adReserved: '预留广告位', hero: '构建可辩护的合成研究', subhero: '以当前来源、人口假设和独立模型审查为方向性面板提供依据。', question: '研究问题', audience: '受众', audiencePlaceholder: '例如：远程知识工作者 · 25–54 岁', market: '市场', global: '全球', reportLanguage: '报告语言', sourceLanguage: '来源语言', anyLanguage: '任何语言', units: '模拟单位', notPeople: '并非受访者', sources: '证据来源', optionalUrls: '可选公开网址', addSource: '添加来源', removeSource: '删除来源', run: '运行有依据的研究', running: '研究代理运行中…', assumptions: '假设', assumptionsLabel: '模型可使用的假设', assumptionsNote: '无支持的假设会在证据账本中标注。', readySources: '已准备 {sources} 个来源和 {assumptions} 个假设。', autoEvidence: 'Likerts 将通过 Vercel AI Gateway 运行两次有限网页搜索，并披露检索到的来源。', progress: '研究进度', frame: '定义', search: '搜索', simulate: '模拟', review: '审查', complete: '完成', fallback: '使用回退', inProgress: '进行中', queued: '排队中', runLabel: '运行', notStarted: '未开始', copyRun: '复制运行 ID', overview: '概览', segments: '细分', verbatims: '回答', evidence: '证据', method: '方法', export: '导出证据包', replay: '重放', likely: '可能', unlikely: '不太可能', unsure: '不确定', hypothesis: '请将其视为待验证假设，而不是市场估计。', suggest: '模型给出的提示', changeRead: '什么会改变这一判断', ledger: '研究账本', coverage: '证据覆盖度', populationFit: '人群匹配度', independentReview: '独立审查', inspectEvidence: '查看证据', marketLabel: '市场', outputLabel: '报告', directional: '方向性合成估计——不是观察到的人类证据。', methodological: '方法学置信度',
  },
  'ja-JP': {
    free: '無料 · アカウント不要', ad: '広告', adReserved: '広告枠', hero: '説明可能な合成調査を作成', subhero: '最新の情報源、母集団の前提、独立したモデルレビューに基づく方向性パネル。', question: '調査質問', audience: '対象者', audiencePlaceholder: '例：リモート知識労働者 · 25～54歳', market: '市場', global: 'グローバル', reportLanguage: 'レポート言語', sourceLanguage: '情報源の言語', anyLanguage: 'すべての言語', units: 'シミュレーション単位', notPeople: '実際の回答者ではありません', sources: '証拠情報源', optionalUrls: '任意の公開URL', addSource: '情報源を追加', removeSource: '情報源を削除', run: '根拠付き調査を実行', running: '調査エージェント実行中…', assumptions: '前提', assumptionsLabel: 'モデルが使用できる前提', assumptionsNote: '裏付けのない前提は証拠台帳に表示されます。', readySources: '{sources}件の情報源と{assumptions}件の前提で準備完了。', autoEvidence: 'Likerts は Vercel AI Gateway で限定的なウェブ検索を2回行い、取得元を開示します。', progress: '調査の進捗', frame: '設計', search: '検索', simulate: '模擬', review: 'レビュー', complete: '完了', fallback: '代替を使用', inProgress: '進行中', queued: '待機中', runLabel: '実行', notStarted: '未開始', copyRun: '実行IDをコピー', overview: '概要', segments: 'セグメント', verbatims: '回答例', evidence: '証拠', method: '方法', export: '証拠パックを出力', replay: '再実行', likely: '可能性あり', unlikely: '可能性低い', unsure: '不明', hypothesis: '市場推定ではなく、検証すべき仮説として扱ってください。', suggest: 'モデルの示唆', changeRead: 'この判断を変えるもの', ledger: '調査台帳', coverage: '証拠カバレッジ', populationFit: '母集団適合度', independentReview: '独立レビュー', inspectEvidence: '証拠を見る', marketLabel: '市場', outputLabel: 'レポート', directional: '方向性の合成推定値 — 観察された人間の証拠ではありません。', methodological: '方法論的信頼度',
  },
  'ko-KR': {
    free: '무료 · 계정 불필요', ad: '광고', adReserved: '광고 영역', hero: '방어 가능한 합성 연구 만들기', subhero: '최신 출처, 모집단 가정, 독립 모델 검토를 기반으로 방향성 패널을 구성합니다.', question: '연구 질문', audience: '대상', audiencePlaceholder: '예: 원격 지식 근로자 · 25–54세', market: '시장', global: '글로벌', reportLanguage: '보고서 언어', sourceLanguage: '출처 언어', anyLanguage: '모든 언어', units: '시뮬레이션 단위', notPeople: '실제 설문 응답자 아님', sources: '근거 출처', optionalUrls: '선택적 공개 URL', addSource: '출처 추가', removeSource: '출처 삭제', run: '근거 기반 연구 실행', running: '연구 에이전트 실행 중…', assumptions: '가정', assumptionsLabel: '모델이 사용할 수 있는 가정', assumptionsNote: '근거 없는 가정은 근거 원장에 표시됩니다.', readySources: '출처 {sources}개와 가정 {assumptions}개로 준비됨.', autoEvidence: 'Likerts는 Vercel AI Gateway로 제한된 웹 검색을 두 번 실행하고 검색 출처를 공개합니다.', progress: '연구 진행 상황', frame: '설계', search: '검색', simulate: '시뮬레이션', review: '검토', complete: '완료', fallback: '대체 사용', inProgress: '진행 중', queued: '대기 중', runLabel: '실행', notStarted: '시작 전', copyRun: '실행 ID 복사', overview: '개요', segments: '세그먼트', verbatims: '응답 예시', evidence: '근거', method: '방법', export: '근거 팩 내보내기', replay: '다시 실행', likely: '가능성 있음', unlikely: '가능성 낮음', unsure: '불확실', hypothesis: '시장 추정치가 아니라 검증할 가설로 다루세요.', suggest: '모델이 제안하는 것', changeRead: '이 해석을 바꿀 요인', ledger: '연구 원장', coverage: '근거 범위', populationFit: '모집단 적합도', independentReview: '독립 검토', inspectEvidence: '근거 확인', marketLabel: '시장', outputLabel: '보고서', directional: '방향성 합성 추정치 — 관찰된 인간 근거가 아닙니다.', methodological: '방법론적 신뢰도',
  },
  'ar-SA': {
    free: 'مجاني · بلا حساب', ad: 'إعلان', adReserved: 'مساحة إعلانية محجوزة', hero: 'أنشئ دراسة تركيبية قابلة للدفاع', subhero: 'أسّس لوحة اتجاهية على مصادر حديثة وافتراضات سكانية ومراجعة مستقلة للنماذج.', question: 'سؤال البحث', audience: 'الجمهور', audiencePlaceholder: 'مثال: العاملون عن بُعد · 25–54 سنة', market: 'السوق', global: 'عالمي', reportLanguage: 'لغة التقرير', sourceLanguage: 'لغة المصادر', anyLanguage: 'أي لغة', units: 'وحدات المحاكاة', notPeople: 'ليست أشخاصاً تم استطلاعهم', sources: 'مصادر الأدلة', optionalUrls: 'روابط عامة اختيارية', addSource: 'إضافة مصدر', removeSource: 'حذف المصدر', run: 'تشغيل دراسة مؤسّسة', running: 'وكلاء البحث يعملون…', assumptions: 'الافتراضات', assumptionsLabel: 'افتراضات يمكن للنماذج استخدامها', assumptionsNote: 'تُعلّم الافتراضات غير المدعومة في سجل الأدلة.', readySources: 'جاهز مع {sources} مصدر و{assumptions} افتراض.', autoEvidence: 'سيجري Likerts عمليتي بحث محدودتين عبر Vercel AI Gateway ويكشف المصادر المسترجعة.', progress: 'تقدم البحث', frame: 'تأطير', search: 'بحث', simulate: 'محاكاة', review: 'مراجعة', complete: 'مكتمل', fallback: 'استُخدم البديل', inProgress: 'قيد التنفيذ', queued: 'في الانتظار', runLabel: 'التشغيل', notStarted: 'لم يبدأ', copyRun: 'نسخ معرّف التشغيل', overview: 'نظرة عامة', segments: 'شرائح', verbatims: 'إجابات', evidence: 'الأدلة', method: 'المنهج', export: 'تصدير حزمة الأدلة', replay: 'إعادة', likely: 'مرجّح', unlikely: 'غير مرجّح', unsure: 'غير مؤكد', hypothesis: 'تعامل معها كفرضية للاختبار، لا كتقدير للسوق.', suggest: 'ما تقترحه النماذج', changeRead: 'ما الذي سيغيّر هذه القراءة', ledger: 'سجل البحث', coverage: 'تغطية الأدلة', populationFit: 'ملاءمة السكان', independentReview: 'مراجعة مستقلة', inspectEvidence: 'فحص الأدلة', marketLabel: 'السوق', outputLabel: 'التقرير', directional: 'تقدير تركيبي اتجاهي — وليس دليلاً بشرياً ملحوظاً.', methodological: 'الثقة المنهجية',
  },
  'hi-IN': {
    free: 'मुफ़्त · खाता आवश्यक नहीं', ad: 'विज्ञापन', adReserved: 'आरक्षित विज्ञापन स्थान', hero: 'एक विश्वसनीय सिंथेटिक अध्ययन बनाएँ', subhero: 'वर्तमान स्रोतों, जनसंख्या मान्यताओं और स्वतंत्र मॉडल समीक्षा पर दिशात्मक पैनल आधारित करें।', question: 'शोध प्रश्न', audience: 'ऑडियंस', audiencePlaceholder: 'जैसे दूरस्थ नॉलेज वर्कर · आयु 25–54', market: 'बाज़ार', global: 'वैश्विक', reportLanguage: 'रिपोर्ट की भाषा', sourceLanguage: 'स्रोत की भाषा', anyLanguage: 'कोई भी भाषा', units: 'सिमुलेशन इकाइयाँ', notPeople: 'सर्वे किए गए लोग नहीं', sources: 'साक्ष्य स्रोत', optionalUrls: 'वैकल्पिक सार्वजनिक URL', addSource: 'स्रोत जोड़ें', removeSource: 'स्रोत हटाएँ', run: 'आधारित अध्ययन चलाएँ', running: 'रिसर्च एजेंट चल रहे हैं…', assumptions: 'मान्यताएँ', assumptionsLabel: 'मॉडल द्वारा उपयोग की जा सकने वाली मान्यताएँ', assumptionsNote: 'असमर्थित मान्यताएँ साक्ष्य लेजर में चिह्नित होती हैं।', readySources: '{sources} स्रोत और {assumptions} मान्यताओं के साथ तैयार।', autoEvidence: 'Likerts, Vercel AI Gateway से दो सीमित वेब खोज चलाकर हर स्रोत दिखाएगा।', progress: 'शोध प्रगति', frame: 'ढाँचा', search: 'खोज', simulate: 'सिमुलेट', review: 'समीक्षा', complete: 'पूर्ण', fallback: 'वैकल्पिक उपयोग', inProgress: 'चल रहा है', queued: 'कतार में', runLabel: 'रन', notStarted: 'शुरू नहीं', copyRun: 'रन ID कॉपी करें', overview: 'अवलोकन', segments: 'सेगमेंट', verbatims: 'प्रतिक्रियाएँ', evidence: 'साक्ष्य', method: 'विधि', export: 'साक्ष्य पैक निर्यात करें', replay: 'दोहराएँ', likely: 'संभावित', unlikely: 'असंभावित', unsure: 'अनिश्चित', hypothesis: 'इसे परीक्षण योग्य परिकल्पना मानें, बाज़ार अनुमान नहीं।', suggest: 'मॉडल क्या सुझाते हैं', changeRead: 'इस निष्कर्ष को क्या बदलेगा', ledger: 'शोध लेजर', coverage: 'साक्ष्य कवरेज', populationFit: 'जनसंख्या अनुकूलता', independentReview: 'स्वतंत्र समीक्षा', inspectEvidence: 'साक्ष्य देखें', marketLabel: 'बाज़ार', outputLabel: 'रिपोर्ट', directional: 'दिशात्मक सिंथेटिक अनुमान — देखा गया मानवीय साक्ष्य नहीं।', methodological: 'पद्धतिगत भरोसा',
  },
};

const I18nContext = createContext({ locale: 'en-US', dir: 'ltr', t: (key) => en[key] || key });

function interpolate(value, variables = {}) {
  return Object.entries(variables).reduce((text, [key, replacement]) => text.replaceAll(`{${key}}`, String(replacement)), value);
}

export function I18nProvider({ locale, children }) {
  const value = useMemo(() => {
    const dictionary = dictionaries[locale] || en;
    const option = languageOptions.find((item) => item.value === locale) || languageOptions[0];
    return {
      locale: option.value,
      dir: option.dir,
      t: (key, variables) => interpolate(dictionary[key] || en[key] || key, variables),
    };
  }, [locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  return useContext(I18nContext);
}

export function getLanguageName(locale) {
  return languageOptions.find((item) => item.value === locale)?.nativeLabel || locale;
}
