import { createContext, useContext, useMemo } from 'react';

export const languageOptions = [
  { value: 'en-US', label: 'English', nativeLabel: 'English', dir: 'ltr' },
  { value: 'es-ES', label: 'Spanish', nativeLabel: 'Español', dir: 'ltr' },
  { value: 'pt-BR', label: 'Portuguese', nativeLabel: 'Português', dir: 'ltr' },
  { value: 'fr-FR', label: 'French', nativeLabel: 'Français', dir: 'ltr' },
  { value: 'de-DE', label: 'German', nativeLabel: 'Deutsch', dir: 'ltr' },
  { value: 'zh-CN', label: 'Chinese', nativeLabel: '简体中文', dir: 'ltr' },
  { value: 'ja-JP', label: 'Japanese', nativeLabel: '日本語', dir: 'ltr' },
  { value: 'ko-KR', label: 'Korean', nativeLabel: '한국어', dir: 'ltr' },
  { value: 'ar-SA', label: 'Arabic', nativeLabel: 'العربية', dir: 'rtl' },
  { value: 'hi-IN', label: 'Hindi', nativeLabel: 'हिन्दी', dir: 'ltr' },
];

const en = {
  free: 'Free to use · no account required', ad: 'Advertisement', adReserved: 'Reserved ad inventory',
  hero: 'Free synthetic market research, grounded in current sources', subhero: 'Test concepts and audience hypotheses with market-aware evidence, explicit assumptions, and multi-model review—no account required.',
  question: 'Research question', audience: 'Audience', audiencePlaceholder: 'e.g. Remote knowledge workers · Ages 25–54', market: 'Market', global: 'Global',
  reportLanguage: 'Report language', sourceLanguage: 'Source language', anyLanguage: 'Any language', units: 'Simulation units', notPeople: 'not surveyed people',
  sources: 'Evidence sources', optionalUrls: 'optional public URLs', addSource: 'Add source', removeSource: 'Remove source', run: 'Run grounded study', running: 'Running research agents…',
  assumptions: 'Assumptions', assumptionsLabel: 'Assumptions the models may use', assumptionsNote: 'Unsupported assumptions are labeled in the evidence ledger.',
  readySources: 'Ready with {sources} supplied source(s) and {assumptions} assumption(s).',
  autoEvidence: 'Likerts will run two bounded web searches through Vercel AI Gateway and disclose retrieved sources. If retrieval fails, the run is labeled prior-only.',
  progress: 'Research run progress', frame: 'Frame', search: 'Search', simulate: 'Simulate', review: 'Review', complete: 'Complete', fallback: 'Fallback used', inProgress: 'In progress', queued: 'Queued', runLabel: 'Run', notStarted: 'not started', copyRun: 'Copy run ID',
  overview: 'Overview', segments: 'Segments', verbatims: 'Verbatims', evidence: 'Evidence', method: 'Method', export: 'Export evidence pack', replay: 'Replay',
  likely: 'likely', unlikely: 'unlikely', unsure: 'unsure', hypothesis: 'Treat this as a hypothesis to test, not a market estimate.', suggest: 'What the models suggest', changeRead: 'What would change this read',
  ledger: 'Research ledger', coverage: 'Evidence coverage', populationFit: 'Population fit', independentReview: 'Independent review', inspectEvidence: 'Inspect evidence', marketLabel: 'Market', outputLabel: 'Report',
  directional: 'Directional synthetic estimate — not observed human evidence.', methodological: 'methodological confidence',
  newStudy: 'New study', editBrief: 'Edit brief', editBriefNote: 'Adjust the question, audience, market, or assumptions.', closeBrief: 'Close brief', completed: 'Completed', illustrativePreview: 'Illustrative preview', currentSources: 'Current sources', noExternalSources: 'No external sources', independentlyReviewed: 'Independently reviewed', reviewNotRun: 'Independent review not run', runId: 'Run ID', reportTab: 'Report', topLineFinding: 'Top-line finding', syntheticDisclosure: 'Synthetic estimates are model-generated, not observed survey results.', executiveInterpretation: 'Executive interpretation', appearsDrive: 'What appears to drive the result', couldChange: 'What could change it', modelInference: 'Model inference', humanValidation: 'Human validation', knownLimitation: 'Known limitation', hypothesisNext: 'Next hypothesis to test', segmentsTitle: 'Segment read', segmentsNote: 'Directional differences across modeled segments; not population measurements.', segmentLabel: 'Segment', directionalDistribution: 'Directional distribution', syntheticVerbatims: 'Synthetic verbatims', possibleReasoning: 'Possible reasoning', verbatimNote: 'Illustrative model-generated language', notInterviewNote: 'These are not interview transcripts or participant quotes.', evidenceLedger: 'Evidence ledger', traceClaimBasis: 'Trace each claim to its basis', evidenceLedgerNote: 'Review sources, assumptions, model inferences, and validation status.', claimOrSource: 'Claim or source', evidenceClassLabel: 'Evidence class', traceLabel: 'Trace', riskLabel: 'Risk', reviewRequired: 'Review required', methodologyLineage: 'Methodology lineage', auditableReplay: 'Auditable replay', replayNote: 'Re-run this study with the recorded inputs and versions.', generatedAt: 'Generated at', promptVersion: 'Prompt version', schemaVersion: 'Schema version', normalizationLabel: 'Normalization', evidenceHash: 'Evidence hash', inputHash: 'Input hash', noEvidenceHash: 'No evidence hash', noInputHash: 'No input hash', knownLimits: 'Known limits', noLineage: 'Lineage not recorded', evidenceAtGlance: 'Evidence at a glance', sourcesCurrent: 'Sources are current', noSourcesNote: 'No external sources were supplied or retrieved.', sourceLanguageLabel: 'Source language', publicWebSource: 'Public web source', modelLineage: 'Model lineage', statusNotRecorded: 'Status not recorded', runDetails: 'Run details', evidenceMode: 'Evidence mode', saved: 'Saved', durable: 'Durable', local: 'Local', session: 'Session', evidenceFooter: 'Synthetic analysis for directional use; validate with human research before decisions.',
};

const reportUiTranslations = {
  'es-ES': {
    newStudy: 'Nuevo estudio', editBrief: 'Editar resumen', editBriefNote: 'Ajusta la pregunta, la audiencia, el mercado o los supuestos.', closeBrief: 'Cerrar resumen', completed: 'Completado', illustrativePreview: 'Vista previa ilustrativa', currentSources: 'Fuentes actuales', noExternalSources: 'Sin fuentes externas', independentlyReviewed: 'Revisado de forma independiente', reviewNotRun: 'No se ejecutó la revisión independiente', runId: 'ID de ejecución', reportTab: 'Informe', topLineFinding: 'Hallazgo principal', syntheticDisclosure: 'Las estimaciones sintéticas son generadas por modelos, no resultados de encuestas observadas.', executiveInterpretation: 'Interpretación ejecutiva', appearsDrive: 'Qué parece impulsar el resultado', couldChange: 'Qué podría cambiarlo', modelInference: 'Inferencia del modelo', humanValidation: 'Validación humana', knownLimitation: 'Limitación conocida', hypothesisNext: 'Siguiente hipótesis que probar', segmentsTitle: 'Lectura por segmentos', segmentsNote: 'Diferencias direccionales entre segmentos modelados; no son mediciones poblacionales.', segmentLabel: 'Segmento', directionalDistribution: 'Distribución direccional', syntheticVerbatims: 'Respuestas sintéticas', possibleReasoning: 'Posible razonamiento', verbatimNote: 'Lenguaje ilustrativo generado por modelos', notInterviewNote: 'No son transcripciones de entrevistas ni citas de participantes.', evidenceLedger: 'Registro de evidencia', traceClaimBasis: 'Rastrea cada afirmación hasta su base', evidenceLedgerNote: 'Revisa las fuentes, los supuestos, las inferencias del modelo y el estado de validación.', claimOrSource: 'Afirmación o fuente', evidenceClassLabel: 'Clase de evidencia', traceLabel: 'Rastreo', riskLabel: 'Riesgo', reviewRequired: 'Revisión necesaria', methodologyLineage: 'Trazabilidad metodológica', auditableReplay: 'Repetición auditable', replayNote: 'Repite este estudio con las entradas y versiones registradas.', generatedAt: 'Generado el', promptVersion: 'Versión del prompt', schemaVersion: 'Versión del esquema', normalizationLabel: 'Normalización', evidenceHash: 'Hash de evidencia', inputHash: 'Hash de entrada', noEvidenceHash: 'Sin hash de evidencia', noInputHash: 'Sin hash de entrada', knownLimits: 'Límites conocidos', noLineage: 'Trazabilidad no registrada', evidenceAtGlance: 'Evidencia de un vistazo', sourcesCurrent: 'Las fuentes están actualizadas', noSourcesNote: 'No se proporcionaron ni recuperaron fuentes externas.', sourceLanguageLabel: 'Idioma de las fuentes', publicWebSource: 'Fuente web pública', modelLineage: 'Trazabilidad del modelo', statusNotRecorded: 'Estado no registrado', runDetails: 'Detalles de la ejecución', evidenceMode: 'Modo de evidencia', saved: 'Guardado', durable: 'Persistente', local: 'Local', session: 'Sesión', evidenceFooter: 'Análisis sintético de uso direccional; valida con investigación humana antes de decidir.',
  },
  'pt-BR': {
    newStudy: 'Novo estudo', editBrief: 'Editar briefing', editBriefNote: 'Ajuste a pergunta, o público, o mercado ou as premissas.', closeBrief: 'Fechar briefing', completed: 'Concluído', illustrativePreview: 'Prévia ilustrativa', currentSources: 'Fontes atuais', noExternalSources: 'Sem fontes externas', independentlyReviewed: 'Revisado de forma independente', reviewNotRun: 'A revisão independente não foi executada', runId: 'ID da execução', reportTab: 'Relatório', topLineFinding: 'Principal descoberta', syntheticDisclosure: 'As estimativas sintéticas são geradas por modelos, não resultados de pesquisas observados.', executiveInterpretation: 'Interpretação executiva', appearsDrive: 'O que parece impulsionar o resultado', couldChange: 'O que poderia mudá-lo', modelInference: 'Inferência do modelo', humanValidation: 'Validação humana', knownLimitation: 'Limitação conhecida', hypothesisNext: 'Próxima hipótese a testar', segmentsTitle: 'Leitura por segmento', segmentsNote: 'Diferenças direcionais entre segmentos modelados; não são medições populacionais.', segmentLabel: 'Segmento', directionalDistribution: 'Distribuição direcional', syntheticVerbatims: 'Respostas sintéticas', possibleReasoning: 'Possível raciocínio', verbatimNote: 'Linguagem ilustrativa gerada por modelos', notInterviewNote: 'Não são transcrições de entrevistas nem citações de participantes.', evidenceLedger: 'Registro de evidências', traceClaimBasis: 'Rastreie cada afirmação até sua base', evidenceLedgerNote: 'Revise fontes, premissas, inferências do modelo e status de validação.', claimOrSource: 'Afirmação ou fonte', evidenceClassLabel: 'Classe de evidência', traceLabel: 'Rastreio', riskLabel: 'Risco', reviewRequired: 'Revisão necessária', methodologyLineage: 'Linhas de método', auditableReplay: 'Reexecução auditável', replayNote: 'Execute novamente este estudo com as entradas e versões registradas.', generatedAt: 'Gerado em', promptVersion: 'Versão do prompt', schemaVersion: 'Versão do esquema', normalizationLabel: 'Normalização', evidenceHash: 'Hash da evidência', inputHash: 'Hash da entrada', noEvidenceHash: 'Sem hash da evidência', noInputHash: 'Sem hash da entrada', knownLimits: 'Limites conhecidos', noLineage: 'Linhas não registradas', evidenceAtGlance: 'Evidências em resumo', sourcesCurrent: 'As fontes estão atuais', noSourcesNote: 'Nenhuma fonte externa foi fornecida ou recuperada.', sourceLanguageLabel: 'Idioma das fontes', publicWebSource: 'Fonte pública da web', modelLineage: 'Linhas do modelo', statusNotRecorded: 'Status não registrado', runDetails: 'Detalhes da execução', evidenceMode: 'Modo de evidência', saved: 'Salvo', durable: 'Persistente', local: 'Local', session: 'Sessão', evidenceFooter: 'Análise sintética para uso direcional; valide com pesquisa humana antes de decidir.',
  },
  'fr-FR': {
    newStudy: 'Nouvelle étude', editBrief: 'Modifier le brief', editBriefNote: 'Ajustez la question, l’audience, le marché ou les hypothèses.', closeBrief: 'Fermer le brief', completed: 'Terminé', illustrativePreview: 'Aperçu illustratif', currentSources: 'Sources actuelles', noExternalSources: 'Aucune source externe', independentlyReviewed: 'Revu indépendamment', reviewNotRun: 'Revue indépendante non effectuée', runId: 'ID de l’exécution', reportTab: 'Rapport', topLineFinding: 'Résultat clé', syntheticDisclosure: 'Les estimations synthétiques sont générées par des modèles, et non issues de réponses observées.', executiveInterpretation: 'Interprétation pour dirigeants', appearsDrive: 'Ce qui semble expliquer le résultat', couldChange: 'Ce qui pourrait le changer', modelInference: 'Inférence du modèle', humanValidation: 'Validation humaine', knownLimitation: 'Limite connue', hypothesisNext: 'Prochaine hypothèse à tester', segmentsTitle: 'Lecture par segment', segmentsNote: 'Différences directionnelles entre segments modélisés ; ce ne sont pas des mesures de population.', segmentLabel: 'Segment', directionalDistribution: 'Distribution directionnelle', syntheticVerbatims: 'Verbatims synthétiques', possibleReasoning: 'Raisonnement possible', verbatimNote: 'Formulation illustrative générée par les modèles', notInterviewNote: 'Il ne s’agit ni de transcriptions d’entretiens ni de citations de participants.', evidenceLedger: 'Registre des preuves', traceClaimBasis: 'Relier chaque affirmation à son fondement', evidenceLedgerNote: 'Examinez les sources, hypothèses, inférences du modèle et l’état de validation.', claimOrSource: 'Affirmation ou source', evidenceClassLabel: 'Classe de preuve', traceLabel: 'Traçabilité', riskLabel: 'Risque', reviewRequired: 'Revue requise', methodologyLineage: 'Traçabilité méthodologique', auditableReplay: 'Rejeu auditable', replayNote: 'Relancez cette étude avec les entrées et versions enregistrées.', generatedAt: 'Généré le', promptVersion: 'Version du prompt', schemaVersion: 'Version du schéma', normalizationLabel: 'Normalisation', evidenceHash: 'Hash des preuves', inputHash: 'Hash des entrées', noEvidenceHash: 'Aucun hash de preuve', noInputHash: 'Aucun hash d’entrée', knownLimits: 'Limites connues', noLineage: 'Traçabilité non enregistrée', evidenceAtGlance: 'Les preuves en un coup d’œil', sourcesCurrent: 'Les sources sont actuelles', noSourcesNote: 'Aucune source externe n’a été fournie ou récupérée.', sourceLanguageLabel: 'Langue des sources', publicWebSource: 'Source web publique', modelLineage: 'Traçabilité du modèle', statusNotRecorded: 'Statut non enregistré', runDetails: 'Détails de l’exécution', evidenceMode: 'Mode de preuve', saved: 'Enregistré', durable: 'Durable', local: 'Local', session: 'Session', evidenceFooter: 'Analyse synthétique à usage directionnel ; validez par une recherche humaine avant toute décision.',
  },
  'de-DE': {
    newStudy: 'Neue Studie', editBrief: 'Brief bearbeiten', editBriefNote: 'Frage, Zielgruppe, Markt oder Annahmen anpassen.', closeBrief: 'Brief schließen', completed: 'Abgeschlossen', illustrativePreview: 'Illustrative Vorschau', currentSources: 'Aktuelle Quellen', noExternalSources: 'Keine externen Quellen', independentlyReviewed: 'Unabhängig geprüft', reviewNotRun: 'Unabhängige Prüfung nicht durchgeführt', runId: 'Lauf-ID', reportTab: 'Bericht', topLineFinding: 'Kernergebnis', syntheticDisclosure: 'Synthetische Schätzungen werden von Modellen erzeugt und sind keine beobachteten Umfrageergebnisse.', executiveInterpretation: 'Zusammenfassung für Führungskräfte', appearsDrive: 'Was das Ergebnis offenbar antreibt', couldChange: 'Was es ändern könnte', modelInference: 'Model Schlussfolgerung', humanValidation: 'Menschliche Validierung', knownLimitation: 'Bekannte Einschränkung', hypothesisNext: 'Nächste zu prüfende Hypothese', segmentsTitle: 'Segmentauswertung', segmentsNote: 'Richtungsweisende Unterschiede zwischen modellierten Segmenten; keine Messungen der Gesamtbevölkerung.', segmentLabel: 'Segment', directionalDistribution: 'Richtungsverteilung', syntheticVerbatims: 'Synthetische Antworten', possibleReasoning: 'Mögliche Begründung', verbatimNote: 'Illustrative, von Modellen erzeugte Formulierung', notInterviewNote: 'Dies sind weder Interviewtranskripte noch Zitate von Teilnehmenden.', evidenceLedger: 'Evidenzprotokoll', traceClaimBasis: 'Jede Aussage auf ihre Grundlage zurückführen', evidenceLedgerNote: 'Quellen, Annahmen, Modellinferenzen und Validierungsstatus prüfen.', claimOrSource: 'Aussage oder Quelle', evidenceClassLabel: 'Evidenzklasse', traceLabel: 'Nachverfolgung', riskLabel: 'Risiko', reviewRequired: 'Prüfung erforderlich', methodologyLineage: 'Methodische Rückverfolgbarkeit', auditableReplay: 'Nachprüfbare Wiederholung', replayNote: 'Diese Studie mit den aufgezeichneten Eingaben und Versionen erneut ausführen.', generatedAt: 'Erstellt am', promptVersion: 'Prompt-Version', schemaVersion: 'Schema-Version', normalizationLabel: 'Normalisierung', evidenceHash: 'Evidenz-Hash', inputHash: 'Eingabe-Hash', noEvidenceHash: 'Kein Evidenz-Hash', noInputHash: 'Kein Eingabe-Hash', knownLimits: 'Bekannte Grenzen', noLineage: 'Rückverfolgbarkeit nicht aufgezeichnet', evidenceAtGlance: 'Evidenz auf einen Blick', sourcesCurrent: 'Quellen sind aktuell', noSourcesNote: 'Es wurden keine externen Quellen bereitgestellt oder abgerufen.', sourceLanguageLabel: 'Quellsprache', publicWebSource: 'Öffentliche Webquelle', modelLineage: 'Modell-Rückverfolgbarkeit', statusNotRecorded: 'Status nicht aufgezeichnet', runDetails: 'Laufdetails', evidenceMode: 'Evidenzmodus', saved: 'Gespeichert', durable: 'Dauerhaft', local: 'Lokal', session: 'Sitzung', evidenceFooter: 'Synthetische Analyse zur richtungsweisenden Nutzung; vor Entscheidungen durch menschliche Forschung validieren.',
  },
  'zh-CN': {
    newStudy: '新建研究', editBrief: '编辑研究简报', editBriefNote: '调整研究问题、受众、市场或假设。', closeBrief: '关闭简报', completed: '已完成', illustrativePreview: '示意预览', currentSources: '当前来源', noExternalSources: '没有外部来源', independentlyReviewed: '已独立审查', reviewNotRun: '尚未进行独立审查', runId: '运行 ID', reportTab: '报告', topLineFinding: '核心发现', syntheticDisclosure: '合成估计由模型生成，并非观察到的调查结果。', executiveInterpretation: '管理层解读', appearsDrive: '哪些因素似乎推动了结果', couldChange: '哪些因素可能改变结果', modelInference: '模型推断', humanValidation: '人工验证', knownLimitation: '已知局限', hypothesisNext: '下一步要验证的假设', segmentsTitle: '细分人群解读', segmentsNote: '模型细分人群之间的方向性差异，并非总体测量结果。', segmentLabel: '细分人群', directionalDistribution: '方向性分布', syntheticVerbatims: '合成原话', possibleReasoning: '可能的推理', verbatimNote: '模型生成的示意性表述', notInterviewNote: '这些不是访谈记录，也不是参与者引语。', evidenceLedger: '证据账本', traceClaimBasis: '追溯每项结论的依据', evidenceLedgerNote: '查看来源、假设、模型推断和验证状态。', claimOrSource: '结论或来源', evidenceClassLabel: '证据类别', traceLabel: '追溯', riskLabel: '风险', reviewRequired: '需要审查', methodologyLineage: '方法沿革', auditableReplay: '可审计重放', replayNote: '使用记录的输入和版本重新运行本研究。', generatedAt: '生成时间', promptVersion: '提示词版本', schemaVersion: '架构版本', normalizationLabel: '标准化', evidenceHash: '证据哈希', inputHash: '输入哈希', noEvidenceHash: '无证据哈希', noInputHash: '无输入哈希', knownLimits: '已知限制', noLineage: '未记录沿革', evidenceAtGlance: '证据一览', sourcesCurrent: '来源为最新来源', noSourcesNote: '未提供或检索到外部来源。', sourceLanguageLabel: '来源语言', publicWebSource: '公开网页来源', modelLineage: '模型沿革', statusNotRecorded: '未记录状态', runDetails: '运行详情', evidenceMode: '证据模式', saved: '已保存', durable: '持久', local: '本地', session: '会话', evidenceFooter: '用于方向性判断的合成分析；决策前请通过人工研究验证。',
  },
  'ja-JP': {
    newStudy: '新しい調査', editBrief: '概要を編集', editBriefNote: '調査質問、対象者、市場、前提を調整します。', closeBrief: '概要を閉じる', completed: '完了', illustrativePreview: 'イメージプレビュー', currentSources: '現在の情報源', noExternalSources: '外部情報源なし', independentlyReviewed: '独立レビュー済み', reviewNotRun: '独立レビュー未実行', runId: '実行ID', reportTab: 'レポート', topLineFinding: '主要な発見', syntheticDisclosure: '合成推定はモデルが生成したもので、観測された調査結果ではありません。', executiveInterpretation: 'エグゼクティブ向け解釈', appearsDrive: '結果を左右しているように見える要因', couldChange: '結果を変える可能性があるもの', modelInference: 'モデル推論', humanValidation: '人による検証', knownLimitation: '既知の制約', hypothesisNext: '次に検証する仮説', segmentsTitle: 'セグメント別の見方', segmentsNote: 'モデル化したセグメント間の方向性の違いであり、母集団の測定値ではありません。', segmentLabel: 'セグメント', directionalDistribution: '方向性分布', syntheticVerbatims: '合成回答例', possibleReasoning: '考えられる理由', verbatimNote: 'モデルが生成した説明用の表現', notInterviewNote: 'インタビュー記録や参加者の発言ではありません。', evidenceLedger: '証拠台帳', traceClaimBasis: '各主張の根拠を追跡', evidenceLedgerNote: '情報源、前提、モデル推論、検証状況を確認します。', claimOrSource: '主張または情報源', evidenceClassLabel: '証拠区分', traceLabel: '追跡', riskLabel: 'リスク', reviewRequired: 'レビューが必要', methodologyLineage: '方法論の系譜', auditableReplay: '監査可能な再実行', replayNote: '記録された入力とバージョンでこの調査を再実行します。', generatedAt: '生成日時', promptVersion: 'プロンプトバージョン', schemaVersion: 'スキーマバージョン', normalizationLabel: '正規化', evidenceHash: '証拠ハッシュ', inputHash: '入力ハッシュ', noEvidenceHash: '証拠ハッシュなし', noInputHash: '入力ハッシュなし', knownLimits: '既知の限界', noLineage: '系譜未記録', evidenceAtGlance: '証拠の概要', sourcesCurrent: '情報源は最新です', noSourcesNote: '外部情報源は提供・取得されていません。', sourceLanguageLabel: '情報源の言語', publicWebSource: '公開ウェブ情報源', modelLineage: 'モデルの系譜', statusNotRecorded: 'ステータス未記録', runDetails: '実行の詳細', evidenceMode: '証拠モード', saved: '保存済み', durable: '永続', local: 'ローカル', session: 'セッション', evidenceFooter: '方向性の判断に用いる合成分析です。意思決定前に人による調査で検証してください。',
  },
  'ko-KR': {
    newStudy: '새 연구', editBrief: '브리프 편집', editBriefNote: '질문, 대상, 시장 또는 가정을 조정하세요.', closeBrief: '브리프 닫기', completed: '완료됨', illustrativePreview: '예시 미리보기', currentSources: '현재 출처', noExternalSources: '외부 출처 없음', independentlyReviewed: '독립 검토 완료', reviewNotRun: '독립 검토를 실행하지 않음', runId: '실행 ID', reportTab: '보고서', topLineFinding: '핵심 발견', syntheticDisclosure: '합성 추정치는 모델이 생성한 것이며 관찰된 설문 결과가 아닙니다.', executiveInterpretation: '경영진 해석', appearsDrive: '결과를 이끄는 것으로 보이는 요인', couldChange: '결과를 바꿀 수 있는 요인', modelInference: '모델 추론', humanValidation: '사람의 검증', knownLimitation: '알려진 한계', hypothesisNext: '다음에 검증할 가설', segmentsTitle: '세그먼트 해석', segmentsNote: '모델링된 세그먼트 간 방향성 차이이며 모집단 측정값이 아닙니다.', segmentLabel: '세그먼트', directionalDistribution: '방향성 분포', syntheticVerbatims: '합성 응답 예시', possibleReasoning: '가능한 추론', verbatimNote: '모델이 생성한 예시 문구', notInterviewNote: '인터뷰 기록이나 참여자의 인용문이 아닙니다.', evidenceLedger: '근거 원장', traceClaimBasis: '각 주장과 근거 연결', evidenceLedgerNote: '출처, 가정, 모델 추론 및 검증 상태를 확인하세요.', claimOrSource: '주장 또는 출처', evidenceClassLabel: '근거 분류', traceLabel: '추적', riskLabel: '위험', reviewRequired: '검토 필요', methodologyLineage: '방법론 계보', auditableReplay: '감사 가능한 재실행', replayNote: '기록된 입력과 버전으로 이 연구를 다시 실행하세요.', generatedAt: '생성 시각', promptVersion: '프롬프트 버전', schemaVersion: '스키마 버전', normalizationLabel: '정규화', evidenceHash: '근거 해시', inputHash: '입력 해시', noEvidenceHash: '근거 해시 없음', noInputHash: '입력 해시 없음', knownLimits: '알려진 제한', noLineage: '계보가 기록되지 않음', evidenceAtGlance: '한눈에 보는 근거', sourcesCurrent: '출처가 최신임', noSourcesNote: '외부 출처가 제공되거나 검색되지 않았습니다.', sourceLanguageLabel: '출처 언어', publicWebSource: '공개 웹 출처', modelLineage: '모델 계보', statusNotRecorded: '상태가 기록되지 않음', runDetails: '실행 세부 정보', evidenceMode: '근거 모드', saved: '저장됨', durable: '영구', local: '로컬', session: '세션', evidenceFooter: '방향성 판단을 위한 합성 분석입니다. 의사결정 전에 사람의 조사로 검증하세요.',
  },
  'ar-SA': {
    newStudy: 'دراسة جديدة', editBrief: 'تعديل الملخص', editBriefNote: 'عدّل السؤال أو الجمهور أو السوق أو الافتراضات.', closeBrief: 'إغلاق الملخص', completed: 'مكتمل', illustrativePreview: 'معاينة توضيحية', currentSources: 'المصادر الحالية', noExternalSources: 'لا توجد مصادر خارجية', independentlyReviewed: 'تمت مراجعته بشكل مستقل', reviewNotRun: 'لم تُجرَ المراجعة المستقلة', runId: 'معرّف التشغيل', reportTab: 'التقرير', topLineFinding: 'النتيجة الرئيسية', syntheticDisclosure: 'التقديرات التركيبية مولّدة بالنماذج وليست نتائج استطلاع ملحوظة.', executiveInterpretation: 'تفسير تنفيذي', appearsDrive: 'ما يبدو أنه يدفع النتيجة', couldChange: 'ما قد يغيّرها', modelInference: 'استنتاج النموذج', humanValidation: 'تحقق بشري', knownLimitation: 'حد معروف', hypothesisNext: 'الفرضية التالية للاختبار', segmentsTitle: 'قراءة الشرائح', segmentsNote: 'فروق اتجاهية بين الشرائح المُنمذجة؛ وليست قياسات للسكان.', segmentLabel: 'الشريحة', directionalDistribution: 'التوزيع الاتجاهي', syntheticVerbatims: 'إجابات تركيبية', possibleReasoning: 'التفسير المحتمل', verbatimNote: 'صياغة توضيحية مولّدة بالنموذج', notInterviewNote: 'هذه ليست نصوص مقابلات أو اقتباسات من مشاركين.', evidenceLedger: 'سجل الأدلة', traceClaimBasis: 'تتبّع أساس كل ادعاء', evidenceLedgerNote: 'راجع المصادر والافتراضات واستنتاجات النموذج وحالة التحقق.', claimOrSource: 'ادعاء أو مصدر', evidenceClassLabel: 'فئة الدليل', traceLabel: 'التتبّع', riskLabel: 'المخاطر', reviewRequired: 'المراجعة مطلوبة', methodologyLineage: 'تسلسل المنهجية', auditableReplay: 'إعادة تشغيل قابلة للتدقيق', replayNote: 'أعد تشغيل هذه الدراسة بالمدخلات والإصدارات المسجلة.', generatedAt: 'تاريخ الإنشاء', promptVersion: 'إصدار الموجّه', schemaVersion: 'إصدار المخطط', normalizationLabel: 'التطبيع', evidenceHash: 'تجزئة الدليل', inputHash: 'تجزئة الإدخال', noEvidenceHash: 'لا توجد تجزئة للدليل', noInputHash: 'لا توجد تجزئة للإدخال', knownLimits: 'الحدود المعروفة', noLineage: 'لم يُسجّل التسلسل', evidenceAtGlance: 'الأدلة في لمحة', sourcesCurrent: 'المصادر حديثة', noSourcesNote: 'لم تُقدَّم أو تُسترجع مصادر خارجية.', sourceLanguageLabel: 'لغة المصادر', publicWebSource: 'مصدر ويب عام', modelLineage: 'تسلسل النموذج', statusNotRecorded: 'الحالة غير مسجلة', runDetails: 'تفاصيل التشغيل', evidenceMode: 'وضع الأدلة', saved: 'محفوظ', durable: 'دائم', local: 'محلي', session: 'جلسة', evidenceFooter: 'تحليل تركيبي للاستخدام الاتجاهي؛ تحقّق ببحث بشري قبل اتخاذ القرارات.',
  },
  'hi-IN': {
    newStudy: 'नया अध्ययन', editBrief: 'ब्रीफ़ संपादित करें', editBriefNote: 'प्रश्न, ऑडियंस, बाज़ार या मान्यताओं को समायोजित करें।', closeBrief: 'ब्रीफ़ बंद करें', completed: 'पूर्ण', illustrativePreview: 'उदाहरणात्मक पूर्वावलोकन', currentSources: 'वर्तमान स्रोत', noExternalSources: 'कोई बाहरी स्रोत नहीं', independentlyReviewed: 'स्वतंत्र रूप से समीक्षा की गई', reviewNotRun: 'स्वतंत्र समीक्षा नहीं चलाई गई', runId: 'रन ID', reportTab: 'रिपोर्ट', topLineFinding: 'मुख्य निष्कर्ष', syntheticDisclosure: 'सिंथेटिक अनुमान मॉडल द्वारा बनाए गए हैं, देखे गए सर्वेक्षण परिणाम नहीं।', executiveInterpretation: 'कार्यकारी व्याख्या', appearsDrive: 'परिणाम को प्रभावित करने वाले संभावित कारक', couldChange: 'इसे क्या बदल सकता है', modelInference: 'मॉडल अनुमान', humanValidation: 'मानवीय सत्यापन', knownLimitation: 'ज्ञात सीमा', hypothesisNext: 'अगली जाँच योग्य परिकल्पना', segmentsTitle: 'सेगमेंट विश्लेषण', segmentsNote: 'मॉडल किए गए सेगमेंट के बीच दिशात्मक अंतर; जनसंख्या माप नहीं।', segmentLabel: 'सेगमेंट', directionalDistribution: 'दिशात्मक वितरण', syntheticVerbatims: 'सिंथेटिक प्रतिक्रियाएँ', possibleReasoning: 'संभावित तर्क', verbatimNote: 'मॉडल द्वारा बनाया गया उदाहरणात्मक पाठ', notInterviewNote: 'ये साक्षात्कार प्रतिलेख या प्रतिभागियों के उद्धरण नहीं हैं।', evidenceLedger: 'साक्ष्य लेजर', traceClaimBasis: 'हर दावे का आधार देखें', evidenceLedgerNote: 'स्रोतों, मान्यताओं, मॉडल अनुमानों और सत्यापन स्थिति की समीक्षा करें।', claimOrSource: 'दावा या स्रोत', evidenceClassLabel: 'साक्ष्य श्रेणी', traceLabel: 'ट्रेस', riskLabel: 'जोखिम', reviewRequired: 'समीक्षा आवश्यक', methodologyLineage: 'पद्धति वंशावली', auditableReplay: 'ऑडिट योग्य पुनःचलाना', replayNote: 'रिकॉर्ड किए गए इनपुट और संस्करणों के साथ यह अध्ययन फिर चलाएँ।', generatedAt: 'निर्माण समय', promptVersion: 'प्रॉम्प्ट संस्करण', schemaVersion: 'स्कीमा संस्करण', normalizationLabel: 'सामान्यीकरण', evidenceHash: 'साक्ष्य हैश', inputHash: 'इनपुट हैश', noEvidenceHash: 'साक्ष्य हैश नहीं', noInputHash: 'इनपुट हैश नहीं', knownLimits: 'ज्ञात सीमाएँ', noLineage: 'वंशावली दर्ज नहीं', evidenceAtGlance: 'एक नज़र में साक्ष्य', sourcesCurrent: 'स्रोत वर्तमान हैं', noSourcesNote: 'कोई बाहरी स्रोत दिया या प्राप्त नहीं किया गया।', sourceLanguageLabel: 'स्रोत भाषा', publicWebSource: 'सार्वजनिक वेब स्रोत', modelLineage: 'मॉडल वंशावली', statusNotRecorded: 'स्थिति दर्ज नहीं', runDetails: 'रन का विवरण', evidenceMode: 'साक्ष्य मोड', saved: 'सहेजा गया', durable: 'स्थायी', local: 'स्थानीय', session: 'सत्र', evidenceFooter: 'दिशात्मक उपयोग के लिए सिंथेटिक विश्लेषण; निर्णय से पहले मानवीय शोध से सत्यापित करें।',
  },
};

const supplementalKeys = [
  'interfaceLanguage', 'notMeasured', 'modelReview', 'modelReviewed', 'copyRunId', 'copied',
  'howItWorks', 'syntheticResearch', 'methodology', 'limitations', 'examples', 'agentDocs',
  'productDocs', 'sourceRecords', 'veryUnlikely', 'notSure', 'veryLikely',
];

const supplementalValues = {
  'en-US': ['Interface language', 'Not measured', 'Model review', 'Model reviewed', 'Copy run ID', 'Copied', 'How it works', 'Synthetic research', 'Methodology', 'Limitations', 'Examples', 'Agent docs', 'Product documentation', 'source records', 'Very unlikely', 'Not sure', 'Very likely'],
  'es-ES': ['Idioma de la interfaz', 'No medido', 'Revisión del modelo', 'Revisado por el modelo', 'Copiar ID de ejecución', 'Copiado', 'Cómo funciona', 'Investigación sintética', 'Metodología', 'Limitaciones', 'Ejemplos', 'Docs para agentes', 'Documentación del producto', 'registros de fuentes', 'Muy improbable', 'No sabe', 'Muy probable'],
  'pt-BR': ['Idioma da interface', 'Não medido', 'Revisão do modelo', 'Revisado pelo modelo', 'Copiar ID da execução', 'Copiado', 'Como funciona', 'Pesquisa sintética', 'Metodologia', 'Limitações', 'Exemplos', 'Docs para agentes', 'Documentação do produto', 'registros de fontes', 'Muito improvável', 'Não sabe', 'Muito provável'],
  'fr-FR': ['Langue de l’interface', 'Non mesuré', 'Revue du modèle', 'Revu par le modèle', 'Copier l’ID d’exécution', 'Copié', 'Fonctionnement', 'Recherche synthétique', 'Méthodologie', 'Limites', 'Exemples', 'Docs agents', 'Documentation produit', 'fiches de sources', 'Très improbable', 'Ne sait pas', 'Très probable'],
  'de-DE': ['Oberflächensprache', 'Nicht gemessen', 'Modellprüfung', 'Vom Modell geprüft', 'Lauf-ID kopieren', 'Kopiert', 'So funktioniert es', 'Synthetische Forschung', 'Methodik', 'Einschränkungen', 'Beispiele', 'Agent-Dokumentation', 'Produktdokumentation', 'Quelleneinträge', 'Sehr unwahrscheinlich', 'Unentschieden', 'Sehr wahrscheinlich'],
  'zh-CN': ['界面语言', '未测量', '模型审查', '已由模型审查', '复制运行 ID', '已复制', '工作原理', '合成研究', '方法论', '局限', '示例', '代理文档', '产品文档', '来源记录', '非常不可能', '不确定', '非常可能'],
  'ja-JP': ['表示言語', '未測定', 'モデルレビュー', 'モデルレビュー済み', '実行 ID をコピー', 'コピーしました', '仕組み', '合成調査', '方法論', '制約', '例', 'エージェント向け資料', '製品ドキュメント', '情報源レコード', 'まったく可能性なし', 'わからない', '非常に可能性あり'],
  'ko-KR': ['인터페이스 언어', '측정 안 됨', '모델 검토', '모델 검토 완료', '실행 ID 복사', '복사됨', '작동 방식', '합성 연구', '방법론', '제한 사항', '예시', '에이전트 문서', '제품 문서', '출처 기록', '전혀 가능성 없음', '잘 모르겠음', '매우 가능성 있음'],
  'ar-SA': ['لغة الواجهة', 'غير مقاس', 'مراجعة النموذج', 'تمت مراجعة النموذج', 'نسخ معرّف التشغيل', 'تم النسخ', 'كيف يعمل', 'البحث التركيبي', 'المنهجية', 'القيود', 'أمثلة', 'وثائق الوكلاء', 'وثائق المنتج', 'سجلات المصادر', 'غير مرجّح إطلاقًا', 'غير متأكد', 'مرجّح جدًا'],
  'hi-IN': ['इंटरफ़ेस भाषा', 'मापा नहीं गया', 'मॉडल समीक्षा', 'मॉडल द्वारा समीक्षित', 'रन ID कॉपी करें', 'कॉपी किया गया', 'यह कैसे काम करता है', 'सिंथेटिक शोध', 'पद्धति', 'सीमाएँ', 'उदाहरण', 'एजेंट दस्तावेज़', 'उत्पाद दस्तावेज़', 'स्रोत रिकॉर्ड', 'बिल्कुल असंभावित', 'निश्चित नहीं', 'बहुत संभावित'],
};

const supplementalUiTranslations = Object.fromEntries(
  Object.entries(supplementalValues).map(([locale, values]) => [locale, Object.fromEntries(supplementalKeys.map((key, index) => [key, values[index]]))]),
);

const evidenceKeys = [
  'sourceTrace', 'assumptionTrace', 'distributionTrace', 'segmentTrace', 'verbatimTrace',
  'groundingRisk', 'notRepresentative', 'segmentNotSampled', 'requiresValidation',
];

const evidenceValues = {
  'en-US': ['Source record → evidence packet', 'Study brief → explicit assumption', 'Framing → panel simulation → model review → normalization', 'Audience frame → model-constructed segments', 'Generated explanations → illustrative themes', 'Grounding only; not independent validation', 'Not representative', 'Segments were not sampled', 'Requires validation'],
  'es-ES': ['Registro de fuente → paquete de evidencia', 'Brief del estudio → supuesto explícito', 'Encuadre → simulación del panel → revisión del modelo → normalización', 'Encuadre de audiencia → segmentos construidos por el modelo', 'Explicaciones generadas → temas ilustrativos', 'Solo contextualización; no es validación independiente', 'No representativo', 'Los segmentos no fueron muestreados', 'Requiere validación'],
  'pt-BR': ['Registro de fonte → pacote de evidências', 'Brief do estudo → premissa explícita', 'Enquadramento → simulação do painel → revisão do modelo → normalização', 'Enquadramento do público → segmentos construídos pelo modelo', 'Explicações geradas → temas ilustrativos', 'Apenas contextualização; não é validação independente', 'Não representativo', 'Os segmentos não foram amostrados', 'Requer validação'],
  'fr-FR': ['Fiche de source → dossier de preuves', 'Brief d’étude → hypothèse explicite', 'Cadrage → simulation du panel → revue du modèle → normalisation', 'Cadrage de l’audience → segments construits par le modèle', 'Explications générées → thèmes illustratifs', 'Contexte uniquement ; aucune validation indépendante', 'Non représentatif', 'Les segments n’ont pas été échantillonnés', 'Validation requise'],
  'de-DE': ['Quelleneintrag → Evidenzpaket', 'Studienbrief → explizite Annahme', 'Rahmung → Panel-Simulation → Modellprüfung → Normalisierung', 'Zielgruppenrahmen → modellkonstruierte Segmente', 'Generierte Erklärungen → illustrative Themen', 'Nur Kontext; keine unabhängige Validierung', 'Nicht repräsentativ', 'Segmente wurden nicht beprobt', 'Validierung erforderlich'],
  'zh-CN': ['来源记录 → 证据包', '研究简报 → 明确假设', '框定 → 面板模拟 → 模型审查 → 标准化', '受众框架 → 模型构建的细分', '生成的解释 → 示意主题', '仅作背景依据；不构成独立验证', '不具代表性', '细分并非抽样所得', '需要验证'],
  'ja-JP': ['情報源レコード → 証拠パック', '調査概要 → 明示的な前提', '枠組み → パネルシミュレーション → モデルレビュー → 正規化', '対象者の枠組み → モデル構築セグメント', '生成された説明 → 例示テーマ', '根拠付けのみ。独立した検証ではありません', '代表性はありません', 'セグメントは抽出標本ではありません', '検証が必要'],
  'ko-KR': ['출처 기록 → 근거 패키지', '연구 브리프 → 명시적 가정', '구성 → 패널 시뮬레이션 → 모델 검토 → 정규화', '대상 프레임 → 모델 구성 세그먼트', '생성된 설명 → 예시 주제', '맥락 제공용이며 독립 검증이 아님', '대표성 없음', '세그먼트는 표본 추출되지 않음', '검증 필요'],
  'ar-SA': ['سجل المصدر ← حزمة الأدلة', 'ملخص الدراسة ← افتراض صريح', 'التأطير ← محاكاة اللوحة ← مراجعة النموذج ← التطبيع', 'إطار الجمهور ← شرائح أنشأها النموذج', 'تفسيرات مولّدة ← موضوعات توضيحية', 'للتأسيس فقط؛ وليست تحققًا مستقلًا', 'غير تمثيلي', 'لم تُسحب عينة للشرائح', 'يتطلب التحقق'],
  'hi-IN': ['स्रोत रिकॉर्ड → साक्ष्य पैक', 'अध्ययन ब्रीफ़ → स्पष्ट मान्यता', 'फ़्रेमिंग → पैनल सिमुलेशन → मॉडल समीक्षा → सामान्यीकरण', 'ऑडियंस फ़्रेम → मॉडल-निर्मित सेगमेंट', 'बनाए गए स्पष्टीकरण → उदाहरणात्मक थीम', 'केवल आधार; स्वतंत्र सत्यापन नहीं', 'प्रतिनिधिक नहीं', 'सेगमेंट का नमूना नहीं लिया गया', 'सत्यापन आवश्यक'],
};

const evidenceUiTranslations = Object.fromEntries(
  Object.entries(evidenceValues).map(([locale, values]) => [locale, Object.fromEntries(evidenceKeys.map((key, index) => [key, values[index]]))]),
);

const dictionaries = {
  'en-US': en,
  'es-ES': {
    free: 'Gratis · sin cuenta', ad: 'Publicidad', adReserved: 'Espacio publicitario reservado', hero: 'Crea un estudio sintético defendible', subhero: 'Fundamenta un panel direccional en fuentes actuales, supuestos de población y revisión independiente de modelos.', question: 'Pregunta de investigación', audience: 'Audiencia', audiencePlaceholder: 'p. ej., profesionales remotos · 25–54 años', market: 'Mercado', global: 'Global', reportLanguage: 'Idioma del informe', sourceLanguage: 'Idioma de las fuentes', anyLanguage: 'Cualquier idioma', units: 'Unidades de simulación', notPeople: 'no son personas encuestadas', sources: 'Fuentes de evidencia', optionalUrls: 'URL públicas opcionales', addSource: 'Añadir fuente', removeSource: 'Eliminar fuente', run: 'Ejecutar estudio fundamentado', running: 'Agentes investigando…', assumptions: 'Supuestos', assumptionsLabel: 'Supuestos que pueden usar los modelos', assumptionsNote: 'Los supuestos sin respaldo se identifican en el registro.', readySources: 'Listo con {sources} fuente(s) y {assumptions} supuesto(s).', autoEvidence: 'Likerts hará dos búsquedas web acotadas mediante Vercel AI Gateway y mostrará las fuentes recuperadas.', progress: 'Progreso del estudio', frame: 'Definir', search: 'Buscar', simulate: 'Simular', review: 'Revisar', complete: 'Completo', fallback: 'Se usó respaldo', inProgress: 'En curso', queued: 'En cola', runLabel: 'Ejecución', notStarted: 'sin iniciar', copyRun: 'Copiar ID', overview: 'Resumen', segments: 'Segmentos', verbatims: 'Respuestas', evidence: 'Evidencia', method: 'Método', export: 'Exportar evidencia', replay: 'Repetir', likely: 'probable', unlikely: 'improbable', unsure: 'duda', hypothesis: 'Trátalo como una hipótesis, no como una estimación de mercado.', suggest: 'Lo que sugieren los modelos', changeRead: 'Qué cambiaría esta lectura', ledger: 'Registro de investigación', coverage: 'Cobertura de evidencia', populationFit: 'Ajuste poblacional', independentReview: 'Revisión independiente', inspectEvidence: 'Ver evidencia', marketLabel: 'Mercado', outputLabel: 'Informe', directional: 'Estimación sintética direccional — no es evidencia humana observada.', methodological: 'confianza metodológica',
  },
  'pt-BR': {
    free: 'Grátis · sem conta', ad: 'Publicidade', adReserved: 'Espaço publicitário reservado', hero: 'Crie um estudo sintético defensável', subhero: 'Fundamente um painel direcional em fontes atuais, premissas populacionais e revisão independente de modelos.', question: 'Pergunta de pesquisa', audience: 'Público', audiencePlaceholder: 'ex.: profissionais remotos · 25–54 anos', market: 'Mercado', global: 'Global', reportLanguage: 'Idioma do relatório', sourceLanguage: 'Idioma das fontes', anyLanguage: 'Qualquer idioma', units: 'Unidades de simulação', notPeople: 'não são pessoas pesquisadas', sources: 'Fontes de evidência', optionalUrls: 'URLs públicas opcionais', addSource: 'Adicionar fonte', removeSource: 'Remover fonte', run: 'Executar estudo fundamentado', running: 'Agentes pesquisando…', assumptions: 'Premissas', assumptionsLabel: 'Premissas que os modelos podem usar', assumptionsNote: 'Premissas sem suporte são marcadas no registro.', readySources: 'Pronto com {sources} fonte(s) e {assumptions} premissa(s).', autoEvidence: 'O Likerts fará duas buscas web limitadas pelo Vercel AI Gateway e mostrará as fontes recuperadas.', progress: 'Progresso da pesquisa', frame: 'Definir', search: 'Buscar', simulate: 'Simular', review: 'Revisar', complete: 'Concluído', fallback: 'Fallback usado', inProgress: 'Em andamento', queued: 'Na fila', runLabel: 'Execução', notStarted: 'não iniciada', copyRun: 'Copiar ID', overview: 'Visão geral', segments: 'Segmentos', verbatims: 'Respostas', evidence: 'Evidência', method: 'Método', export: 'Exportar evidências', replay: 'Repetir', likely: 'provável', unlikely: 'improvável', unsure: 'incerto', hypothesis: 'Trate como hipótese a testar, não como estimativa de mercado.', suggest: 'O que os modelos sugerem', changeRead: 'O que mudaria esta leitura', ledger: 'Registro de pesquisa', coverage: 'Cobertura de evidência', populationFit: 'Adequação populacional', independentReview: 'Revisão independente', inspectEvidence: 'Ver evidência', marketLabel: 'Mercado', outputLabel: 'Relatório', directional: 'Estimativa sintética direcional — não é evidência humana observada.', methodological: 'confiança metodológica',
  },
  'fr-FR': {
    free: 'Gratuit · sans compte', ad: 'Publicité', adReserved: 'Emplacement publicitaire réservé', hero: 'Créez une étude synthétique défendable', subhero: 'Fondez un panel directionnel sur des sources actuelles, des hypothèses de population et une revue indépendante des modèles.', question: 'Question de recherche', audience: 'Audience', audiencePlaceholder: 'ex. télétravailleurs qualifiés · 25–54 ans', market: 'Marché', global: 'Monde', reportLanguage: 'Langue du rapport', sourceLanguage: 'Langue des sources', anyLanguage: 'Toutes les langues', units: 'Unités de simulation', notPeople: 'pas des personnes interrogées', sources: 'Sources de preuve', optionalUrls: 'URL publiques facultatives', addSource: 'Ajouter une source', removeSource: 'Supprimer la source', run: 'Lancer l’étude étayée', running: 'Agents de recherche en cours…', assumptions: 'Hypothèses', assumptionsLabel: 'Hypothèses utilisables par les modèles', assumptionsNote: 'Les hypothèses non étayées sont signalées dans le registre.', readySources: 'Prêt avec {sources} source(s) et {assumptions} hypothèse(s).', autoEvidence: 'Likerts effectuera deux recherches web ciblées via Vercel AI Gateway et indiquera chaque source.', progress: 'Progression de l’étude', frame: 'Cadrer', search: 'Chercher', simulate: 'Simuler', review: 'Réviser', complete: 'Terminé', fallback: 'Solution de repli', inProgress: 'En cours', queued: 'En attente', runLabel: 'Exécution', notStarted: 'non démarrée', copyRun: 'Copier l’ID', overview: 'Vue d’ensemble', segments: 'Segments', verbatims: 'Verbatims', evidence: 'Preuves', method: 'Méthode', export: 'Exporter les preuves', replay: 'Relancer', likely: 'probable', unlikely: 'improbable', unsure: 'incertain', hypothesis: 'Traitez ceci comme une hypothèse, pas comme une estimation de marché.', suggest: 'Ce que suggèrent les modèles', changeRead: 'Ce qui changerait cette lecture', ledger: 'Registre de recherche', coverage: 'Couverture des preuves', populationFit: 'Adéquation population', independentReview: 'Revue indépendante', inspectEvidence: 'Voir les preuves', marketLabel: 'Marché', outputLabel: 'Rapport', directional: 'Estimation synthétique directionnelle — aucune preuve humaine observée.', methodological: 'confiance méthodologique',
  },
  'de-DE': {
    free: 'Kostenlos · kein Konto', ad: 'Werbung', adReserved: 'Reservierte Werbefläche', hero: 'Erstelle eine belastbare synthetische Studie', subhero: 'Stütze ein richtungsweisendes Panel auf aktuelle Quellen, Populationsannahmen und unabhängige Modellprüfung.', question: 'Forschungsfrage', audience: 'Zielgruppe', audiencePlaceholder: 'z. B. Remote-Wissensarbeiter · 25–54 Jahre', market: 'Markt', global: 'Global', reportLanguage: 'Berichtssprache', sourceLanguage: 'Quellsprache', anyLanguage: 'Alle Sprachen', units: 'Simulationseinheiten', notPeople: 'keine befragten Personen', sources: 'Evidenzquellen', optionalUrls: 'optionale öffentliche URLs', addSource: 'Quelle hinzufügen', removeSource: 'Quelle entfernen', run: 'Fundierte Studie starten', running: 'Recherche-Agenten arbeiten…', assumptions: 'Annahmen', assumptionsLabel: 'Annahmen für die Modelle', assumptionsNote: 'Unbelegte Annahmen werden im Evidenzprotokoll markiert.', readySources: 'Bereit mit {sources} Quelle(n) und {assumptions} Annahme(n).', autoEvidence: 'Likerts führt zwei begrenzte Websuchen über Vercel AI Gateway aus und legt alle Quellen offen.', progress: 'Studienfortschritt', frame: 'Rahmen', search: 'Suche', simulate: 'Simulation', review: 'Prüfung', complete: 'Fertig', fallback: 'Fallback genutzt', inProgress: 'In Arbeit', queued: 'Wartend', runLabel: 'Lauf', notStarted: 'nicht gestartet', copyRun: 'Lauf-ID kopieren', overview: 'Überblick', segments: 'Segmente', verbatims: 'Antworten', evidence: 'Evidenz', method: 'Methode', export: 'Evidenz exportieren', replay: 'Wiederholen', likely: 'wahrscheinlich', unlikely: 'unwahrscheinlich', unsure: 'unsicher', hypothesis: 'Als zu testende Hypothese behandeln, nicht als Marktschätzung.', suggest: 'Was die Modelle nahelegen', changeRead: 'Was diese Einschätzung ändern würde', ledger: 'Forschungsprotokoll', coverage: 'Evidenzabdeckung', populationFit: 'Populationspassung', independentReview: 'Unabhängige Prüfung', inspectEvidence: 'Evidenz prüfen', marketLabel: 'Markt', outputLabel: 'Bericht', directional: 'Synthetische Richtungsschätzung — keine beobachtete menschliche Evidenz.', methodological: 'methodische Sicherheit',
  },
  'zh-CN': {
    free: '免费使用 · 无需账户', ad: '广告', adReserved: '预留广告位', hero: '构建可辩护的合成研究', subhero: '以当前来源、人口假设和独立模型审查为方向性面板提供依据。', question: '研究问题', audience: '受众', audiencePlaceholder: '例如：远程知识工作者 · 25–54 岁', market: '市场', global: '全球', reportLanguage: '报告语言', sourceLanguage: '来源语言', anyLanguage: '任何语言', units: '模拟单位', notPeople: '并非受访者', sources: '证据来源', optionalUrls: '可选公开网址', addSource: '添加来源', removeSource: '删除来源', run: '运行有依据的研究', running: '研究代理运行中…', assumptions: '假设', assumptionsLabel: '模型可使用的假设', assumptionsNote: '无支持的假设会在证据账本中标注。', readySources: '已准备 {sources} 个来源和 {assumptions} 个假设。', autoEvidence: 'Likerts 将通过 Vercel AI Gateway 运行两次有限网页搜索，并披露检索到的来源。', progress: '研究进度', frame: '定义', search: '搜索', simulate: '模拟', review: '审查', complete: '完成', fallback: '使用回退', inProgress: '进行中', queued: '排队中', runLabel: '运行', notStarted: '未开始', copyRun: '复制运行 ID', overview: '概览', segments: '细分', verbatims: '回答', evidence: '证据', method: '方法', export: '导出证据包', replay: '重放', likely: '可能', unlikely: '不太可能', unsure: '不确定', hypothesis: '请将其视为待验证假设，而不是市场估计。', suggest: '模型给出的提示', changeRead: '什么会改变这一判断', ledger: '研究账本', coverage: '证据覆盖度', populationFit: '人群匹配度', independentReview: '独立审查', inspectEvidence: '查看证据', marketLabel: '市场', outputLabel: '报告', directional: '方向性合成估计——不是观察到的人类证据。', methodological: '方法学置信度',
  },
  'ja-JP': {
    free: '無料 · アカウント不要', ad: '広告', adReserved: '広告枠', hero: '説明可能な合成調査を作成', subhero: '最新の情報源、母集団の前提、独立したモデルレビューに基づく方向性パネル。', question: '調査質問', audience: '対象者', audiencePlaceholder: '例：リモート知識労働者 · 25～54歳', market: '市場', global: 'グローバル', reportLanguage: 'レポート言語', sourceLanguage: '情報源の言語', anyLanguage: 'すべての言語', units: 'シミュレーション単位', notPeople: '実際の回答者ではありません', sources: '証拠情報源', optionalUrls: '任意の公開URL', addSource: '情報源を追加', removeSource: '情報源を削除', run: '根拠付き調査を実行', running: '調査エージェント実行中…', assumptions: '前提', assumptionsLabel: 'モデルが使用できる前提', assumptionsNote: '裏付けのない前提は証拠台帳に表示されます。', readySources: '{sources}件の情報源と{assumptions}件の前提で準備完了。', autoEvidence: 'Likerts は Vercel AI Gateway で限定的なウェブ検索を2回行い、取得元を開示します。', progress: '調査の進捗', frame: '設計', search: '検索', simulate: '模擬', review: 'レビュー', complete: '完了', fallback: '代替を使用', inProgress: '進行中', queued: '待機中', runLabel: '実行', notStarted: '未開始', copyRun: '実行IDをコピー', overview: '概要', segments: 'セグメント', verbatims: '回答例', evidence: '証拠', method: '方法', export: '証拠パックを出力', replay: '再実行', likely: '可能性あり', unlikely: '可能性低い', unsure: '不明', hypothesis: '市場推定ではなく、検証すべき仮説として扱ってください。', suggest: 'モデルの示唆', changeRead: 'この判断を変えるもの', ledger: '調査台帳', coverage: '証拠カバレッジ', populationFit: '母集団適合度', independentReview: '独立レビュー', inspectEvidence: '証拠を見る', marketLabel: '市場', outputLabel: 'レポート', directional: '方向性の合成推定値 — 観察された人間の証拠ではありません。', methodological: '方法論的信頼度',
  },
  'ko-KR': {
    free: '무료 · 계정 불필요', ad: '광고', adReserved: '광고 영역', hero: '방어 가능한 합성 연구 만들기', subhero: '최신 출처, 모집단 가정, 독립 모델 검토를 기반으로 방향성 패널을 구성합니다.', question: '연구 질문', audience: '대상', audiencePlaceholder: '예: 원격 지식 근로자 · 25–54세', market: '시장', global: '글로벌', reportLanguage: '보고서 언어', sourceLanguage: '출처 언어', anyLanguage: '모든 언어', units: '시뮬레이션 단위', notPeople: '실제 설문 응답자 아님', sources: '근거 출처', optionalUrls: '선택적 공개 URL', addSource: '출처 추가', removeSource: '출처 삭제', run: '근거 기반 연구 실행', running: '연구 에이전트 실행 중…', assumptions: '가정', assumptionsLabel: '모델이 사용할 수 있는 가정', assumptionsNote: '근거 없는 가정은 근거 원장에 표시됩니다.', readySources: '출처 {sources}개와 가정 {assumptions}개로 준비됨.', autoEvidence: 'Likerts는 Vercel AI Gateway로 제한된 웹 검색을 두 번 실행하고 검색 출처를 공개합니다.', progress: '연구 진행 상황', frame: '설계', search: '검색', simulate: '시뮬레이션', review: '검토', complete: '완료', fallback: '대체 사용', inProgress: '진행 중', queued: '대기 중', runLabel: '실행', notStarted: '시작 전', copyRun: '실행 ID 복사', overview: '개요', segments: '세그먼트', verbatims: '응답 예시', evidence: '근거', method: '방법', export: '근거 팩 내보내기', replay: '다시 실행', likely: '가능성 있음', unlikely: '가능성 낮음', unsure: '불확실', hypothesis: '시장 추정치가 아니라 검증할 가설로 다루세요.', suggest: '모델이 제안하는 것', changeRead: '이 해석을 바꿀 요인', ledger: '연구 원장', coverage: '근거 범위', populationFit: '모집단 적합도', independentReview: '독립 검토', inspectEvidence: '근거 확인', marketLabel: '시장', outputLabel: '보고서', directional: '방향성 합성 추정치 — 관찰된 인간 근거가 아닙니다.', methodological: '방법론적 신뢰도',
  },
  'ar-SA': {
    free: 'مجاني · بلا حساب', ad: 'إعلان', adReserved: 'مساحة إعلانية محجوزة', hero: 'أنشئ دراسة تركيبية قابلة للدفاع', subhero: 'أسّس لوحة اتجاهية على مصادر حديثة وافتراضات سكانية ومراجعة مستقلة للنماذج.', question: 'سؤال البحث', audience: 'الجمهور', audiencePlaceholder: 'مثال: العاملون عن بُعد · 25–54 سنة', market: 'السوق', global: 'عالمي', reportLanguage: 'لغة التقرير', sourceLanguage: 'لغة المصادر', anyLanguage: 'أي لغة', units: 'وحدات المحاكاة', notPeople: 'ليست أشخاصاً تم استطلاعهم', sources: 'مصادر الأدلة', optionalUrls: 'روابط عامة اختيارية', addSource: 'إضافة مصدر', removeSource: 'حذف المصدر', run: 'تشغيل دراسة مؤسّسة', running: 'وكلاء البحث يعملون…', assumptions: 'الافتراضات', assumptionsLabel: 'افتراضات يمكن للنماذج استخدامها', assumptionsNote: 'تُعلّم الافتراضات غير المدعومة في سجل الأدلة.', readySources: 'جاهز مع {sources} مصدر و{assumptions} افتراض.', autoEvidence: 'سيجري Likerts عمليتي بحث محدودتين عبر Vercel AI Gateway ويكشف المصادر المسترجعة.', progress: 'تقدم البحث', frame: 'تأطير', search: 'بحث', simulate: 'محاكاة', review: 'مراجعة', complete: 'مكتمل', fallback: 'استُخدم البديل', inProgress: 'قيد التنفيذ', queued: 'في الانتظار', runLabel: 'التشغيل', notStarted: 'لم يبدأ', copyRun: 'نسخ معرّف التشغيل', overview: 'نظرة عامة', segments: 'شرائح', verbatims: 'إجابات', evidence: 'الأدلة', method: 'المنهج', export: 'تصدير حزمة الأدلة', replay: 'إعادة', likely: 'مرجّح', unlikely: 'غير مرجّح', unsure: 'غير مؤكد', hypothesis: 'تعامل معها كفرضية للاختبار، لا كتقدير للسوق.', suggest: 'ما تقترحه النماذج', changeRead: 'ما الذي سيغيّر هذه القراءة', ledger: 'سجل البحث', coverage: 'تغطية الأدلة', populationFit: 'ملاءمة السكان', independentReview: 'مراجعة مستقلة', inspectEvidence: 'فحص الأدلة', marketLabel: 'السوق', outputLabel: 'التقرير', directional: 'تقدير تركيبي اتجاهي — وليس دليلاً بشرياً ملحوظاً.', methodological: 'الثقة المنهجية',
  },
  'hi-IN': {
    free: 'मुफ़्त · खाता आवश्यक नहीं', ad: 'विज्ञापन', adReserved: 'आरक्षित विज्ञापन स्थान', hero: 'एक विश्वसनीय सिंथेटिक अध्ययन बनाएँ', subhero: 'वर्तमान स्रोतों, जनसंख्या मान्यताओं और स्वतंत्र मॉडल समीक्षा पर दिशात्मक पैनल आधारित करें।', question: 'शोध प्रश्न', audience: 'ऑडियंस', audiencePlaceholder: 'जैसे दूरस्थ नॉलेज वर्कर · आयु 25–54', market: 'बाज़ार', global: 'वैश्विक', reportLanguage: 'रिपोर्ट की भाषा', sourceLanguage: 'स्रोत की भाषा', anyLanguage: 'कोई भी भाषा', units: 'सिमुलेशन इकाइयाँ', notPeople: 'सर्वे किए गए लोग नहीं', sources: 'साक्ष्य स्रोत', optionalUrls: 'वैकल्पिक सार्वजनिक URL', addSource: 'स्रोत जोड़ें', removeSource: 'स्रोत हटाएँ', run: 'आधारित अध्ययन चलाएँ', running: 'रिसर्च एजेंट चल रहे हैं…', assumptions: 'मान्यताएँ', assumptionsLabel: 'मॉडल द्वारा उपयोग की जा सकने वाली मान्यताएँ', assumptionsNote: 'असमर्थित मान्यताएँ साक्ष्य लेजर में चिह्नित होती हैं।', readySources: '{sources} स्रोत और {assumptions} मान्यताओं के साथ तैयार।', autoEvidence: 'Likerts, Vercel AI Gateway से दो सीमित वेब खोज चलाकर हर स्रोत दिखाएगा।', progress: 'शोध प्रगति', frame: 'ढाँचा', search: 'खोज', simulate: 'सिमुलेट', review: 'समीक्षा', complete: 'पूर्ण', fallback: 'वैकल्पिक उपयोग', inProgress: 'चल रहा है', queued: 'कतार में', runLabel: 'रन', notStarted: 'शुरू नहीं', copyRun: 'रन ID कॉपी करें', overview: 'अवलोकन', segments: 'सेगमेंट', verbatims: 'प्रतिक्रियाएँ', evidence: 'साक्ष्य', method: 'विधि', export: 'साक्ष्य पैक निर्यात करें', replay: 'दोहराएँ', likely: 'संभावित', unlikely: 'असंभावित', unsure: 'अनिश्चित', hypothesis: 'इसे परीक्षण योग्य परिकल्पना मानें, बाज़ार अनुमान नहीं।', suggest: 'मॉडल क्या सुझाते हैं', changeRead: 'इस निष्कर्ष को क्या बदलेगा', ledger: 'शोध लेजर', coverage: 'साक्ष्य कवरेज', populationFit: 'जनसंख्या अनुकूलता', independentReview: 'स्वतंत्र समीक्षा', inspectEvidence: 'साक्ष्य देखें', marketLabel: 'बाज़ार', outputLabel: 'रिपोर्ट', directional: 'दिशात्मक सिंथेटिक अनुमान — देखा गया मानवीय साक्ष्य नहीं।', methodological: 'पद्धतिगत भरोसा',
  },
};

const I18nContext = createContext({ locale: 'en-US', dir: 'ltr', t: (key) => en[key] || key });

function interpolate(value, variables = {}) {
  return Object.entries(variables).reduce((text, [key, replacement]) => text.replaceAll(`{${key}}`, String(replacement)), value);
}

export function I18nProvider({ locale, children }) {
  const value = useMemo(() => {
    const dictionary = {
      ...(dictionaries[locale] || en),
      ...(reportUiTranslations[locale] || {}),
      ...(supplementalUiTranslations[locale] || supplementalUiTranslations['en-US']),
      ...(evidenceUiTranslations[locale] || evidenceUiTranslations['en-US']),
    };
    const option = languageOptions.find((item) => item.value === locale) || languageOptions[0];
    return {
      locale: option.value,
      dir: option.dir,
      t: (key, variables) => interpolate(dictionary[key] || en[key] || key, variables),
    };
  }, [locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  return useContext(I18nContext);
}

export function getLanguageName(locale) {
  return languageOptions.find((item) => item.value === locale)?.nativeLabel || locale;
}
