name: likerts
version: 0.0.3
publish_to: none
description: Embedded Likerts collection client foundation.
homepage: https://github.com/crosstabs/likerts
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
